apply plugin: 'java'

compileJava {
    options.compilerArgs << '-parameters'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    ivy {
        ivyPattern "https://sissource.ethz.ch/openbis/openbis-public/openbis-ivy/-/raw/main/[organisation]/[module]/[revision]/ivy.xml"
        artifactPattern "https://sissource.ethz.ch/openbis/openbis-public/openbis-ivy/-/raw/main/[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier]).[ext]"
    }
    //mavenCentral()
}

dependencies {

    compileOnly libs.org.projectlombok.lombok
    annotationProcessor libs.org.projectlombok.lombok
    implementation project(':lib-logging'),
            project(':lib-json'),
            project(':api-openbis-java'),
            libs.org.slf4j.slf4j.api,
            libs.org.slf4j.slf4j.jdk14


}

tasks.register('versionUpdate') {
    file('src/core-plugins/eln-lims/1/as/webapps/eln-lims/html/version.txt').write(System.getProperty("version"))
}

clean.dependsOn 'versionUpdate'

//
// Version Management
//

def execute_working_dir(command, arguments, working_dir) {
    new ByteArrayOutputStream().withStream { os ->
        print "execute: ${command}"
        arguments.collect({print " ${it}"})
        println ''
        def result = exec {
            executable = command
            args = arguments
            standardOutput = os
        }
        return os.toString().split('\n')
    }
}

def isGitProject() {
    return new java.io.File(projectDir, ".git").isDirectory() || new java.io.File(projectDir, "../.git").isDirectory()
}

def calculateBuildInfo() {
    if (isGitProject()) {
        def gitlogoutput = execute_working_dir('git', ['log', '-1', '--format=%at'],  "../.git")
        project.ext.revisionNumber = Integer.parseInt(gitlogoutput[0])
    } else {
        project.ext.revisionNumber = 1
    }
    System.setProperty("revision", "" + project.ext.revisionNumber);

    def version = System.getProperty("version")
    if(version == null || version.isEmpty()) {
        project.ext.versionNumber = 'SNAPSHOT'
    } else {
        project.ext.versionNumber = version
    }
    System.setProperty("version", project.ext.versionNumber);

    def versionPlusRevision = project.ext.versionNumber + '+' + project.ext.revisionNumber
    System.setProperty("version+revision", versionPlusRevision);
}

calculateBuildInfo()