#
#   Copyright ETH 2026 Zürich, Scientific IT Services
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
"""Deprecated pybis 1.x aliases, kept for one major release.

Every renamed method gets a shim here that emits a ``DeprecationWarning``
with a migration hint, translates renamed keyword arguments, and delegates
to the new method.  Removed implementation-detail parameters (``only_data``,
``raw_response``, ``use_cache``, ``attrs``) hard-fail with a pointed
``TypeError`` — silently ignoring them would change behavior invisibly.

This module is the only place where the 1.x vocabulary (sample, experiment)
may appear. See ``MIGRATION_GUIDE.md`` for the full mapping.
"""

from __future__ import annotations

import functools
import inspect
import re
import warnings
from typing import Any, Callable, TypeVar

C = TypeVar("C", bound=type)

#: camelCase (and old-vocabulary) keyword arguments → new snake_case names.
_PARAM_RENAMES: dict[str, str] = {
    "permId": "perm_id",
    "withParents": "with_parents",
    "withChildren": "with_children",
    "withAttachments": "with_attachments",
    "withDataSetIds": "with_dataset_ids",
    "projectId": "project_id",
    "userId": "user_id",
    "techId": "tech_id",
    "sessionName": "session_name",
    "validFrom": "valid_from",
    "validTo": "valid_to",
    "vocabularyCode": "vocabulary_code",
    "entityType": "entity_type",
    "propertyType": "property_type",
    "generatedCodePrefix": "generated_code_prefix",
    "subcodeUnique": "subcode_unique",
    "autoGeneratedCode": "auto_generated_code",
    "showContainer": "show_container",
    "showParents": "show_parents",
    "showParentMetadata": "show_parent_metadata",
    "validationPlugin": "validation_plugin",
    "mainDataSetPattern": "main_dataset_pattern",
    "mainDataSetPath": "main_dataset_path",
    "disallowDeletion": "disallow_deletion",
    "managedInternally": "managed_internally",
    "chosenFromList": "chosen_from_list",
    "dataType": "data_type",
    "sampleType": "object_type",
    "materialType": "material_type",
    "pluginType": "plugin_type",
    "userIds": "user_ids",
    "data_set_id": "dataset_id",
    # old vocabulary in parameter names
    "experiment": "collection",
    "sample": "object",
    "sample_ident": "identifier",
}

#: Implementation-detail parameters removed from the public API.
_REMOVED_PARAMS: dict[str, str] = {
    "only_data": (
        "entities are always returned; use entity.data for the raw dict"
    ),
    "raw_response": (
        "raw responses are no longer exposed; use the typed entities"
    ),
    "use_cache": "caching is transparent now; see Openbis.clear_cache()",
    "attrs": "use the returned entities (or result.df) instead",
}

#: Renamed methods: old name → new name. Grows wave by wave; every entry
#: must also appear in MIGRATION_GUIDE.md.
_METHOD_RENAMES: dict[str, str] = {
    "get_spaces": "search_spaces",
    "get_projects": "search_projects",
    # wave 2: objects (samples), collections (experiments), entity types
    "get_samples": "search_objects",
    "get_objects": "search_objects",
    "get_sample": "get_object",
    "new_sample": "new_object",
    "get_experiments": "search_collections",
    "get_collections": "search_collections",
    "get_experiment": "get_collection",
    "new_experiment": "new_collection",
    "get_sample_types": "search_object_types",
    "get_object_types": "search_object_types",
    "get_sample_type": "get_object_type",
    "get_experiment_types": "search_collection_types",
    "get_collection_types": "search_collection_types",
    "get_experiment_type": "get_collection_type",
    "new_sample_type": "new_object_type",
    "new_experiment_type": "new_collection_type",
    # wave 3: datasets
    "get_datasets": "search_datasets",
    "get_dataset_types": "search_dataset_types",
    # wave 4: admin entities
    "get_persons": "search_persons",
    "get_users": "search_persons",
    "get_user": "get_person",
    "get_groups": "search_groups",
    "get_role_assignments": "search_role_assignments",
    "get_terms": "search_terms",
    "get_vocabularies": "search_vocabularies",
    "get_tags": "search_tags",
    "get_deletions": "search_deletions",
}

#: Methods that keep their name but whose 1.x parameters are translated.
#: The wrapper warns only when a legacy parameter was actually used.
_PARAM_SHIMMED: dict[str, list[str]] = {
    # legacy positional order
    "get_dataset": ["permIds"],
    "new_dataset": ["type", "kind", "files", "file", "props", "folder"],
    "get_dataset_type": ["type"],
    "get_person": ["userId"],
    "new_person": ["userId", "space"],
    "new_group": ["code", "description", "userIds"],
    "get_role_assignment": ["techId"],
    "get_term": ["code", "vocabularyCode"],
    "new_term": ["code", "vocabularyCode", "label", "description"],
    "get_vocabulary": ["code"],
    "new_vocabulary": ["code", "terms"],
    "get_tag": ["permId"],
    "new_tag": ["code", "description"],
}

#: Positional parameter names of the legacy signatures, so positional 1.x
#: call styles keep working through the shims.
_LEGACY_POSITIONAL: dict[str, list[str]] = {
    "get_terms": ["vocabulary", "start_with", "count"],
    "get_vocabularies": ["code", "start_with", "count"],
    "get_tags": ["code", "start_with", "count"],
    "get_spaces": ["code", "start_with", "count"],
    "get_projects": ["space", "code", "start_with", "count"],
    "get_samples": [
        "identifier",
        "code",
        "permId",
        "space",
        "project",
        "experiment",
        "collection",
        "type",
        "start_with",
        "count",
    ],
    "get_objects": [
        "identifier",
        "code",
        "permId",
        "space",
        "project",
        "experiment",
        "collection",
        "type",
        "start_with",
        "count",
    ],
    "get_sample": ["sample_ident"],
    "new_sample": ["type", "project", "props"],
    "get_experiments": [
        "code",
        "permId",
        "type",
        "space",
        "project",
        "start_with",
        "count",
    ],
    "get_collections": [
        "code",
        "permId",
        "type",
        "space",
        "project",
        "start_with",
        "count",
    ],
    "get_experiment": ["identifier"],
    "new_experiment": ["type", "code", "project"],
    "get_sample_types": ["type", "start_with", "count"],
    "get_object_types": ["type", "start_with", "count"],
    "get_sample_type": ["type"],
    "get_experiment_types": ["type", "start_with", "count"],
    "get_collection_types": ["type", "start_with", "count"],
    "get_experiment_type": ["type"],
    "new_sample_type": ["code", "generatedCodePrefix"],
    "new_experiment_type": ["code", "description"],
}

#: Per-method parameter handling that differs from the global rename map.
#: A value of None silently absorbs the parameter (obsolete, behavior now
#: built in — e.g. property columns are always part of result.df).
_PER_METHOD_PARAM_RENAMES: dict[str, dict[str, str | None]] = {
    "get_samples": {"props": None},
    "get_objects": {"props": None},
    "get_sample": {"props": None, "withAttachments": None, "withDataSetIds": None},
    "get_experiments": {"props": None},
    "get_collections": {"props": None},
    "get_experiment": {"withAttachments": None},
    "new_sample": {"props": "properties"},
    "new_experiment": {"props": "properties"},
    "get_sample_types": {"type": "code"},
    "get_object_types": {"type": "code"},
    "get_sample_type": {"type": "code"},
    "get_experiment_types": {"type": "code"},
    "get_collection_types": {"type": "code"},
    "get_experiment_type": {"type": "code"},
    "get_datasets": {"props": None},
    "get_dataset": {"permIds": "perm_id", "props": None},
    "new_dataset": {"props": "properties", "file": "files", "zipfile": "zip_file"},
    "get_dataset_types": {"type": "code"},
    "get_dataset_type": {"type": "code"},
    "get_role_assignments": {"user": "person"},
    "get_persons": {"userId": "user_id"},
    "get_terms": {"vocabulary": "vocabulary"},
}

#: Parameters whose 1.x meaning depended on the value: a bool means the
#: fetch flag, anything else is a relationship filter.
_VALUE_DEPENDENT: dict[str, tuple[str, str]] = {
    "withParents": ("with_parents", "parents"),
    "withChildren": ("with_children", "children"),
}

#: Parameters carrying identifying strings; 1.x accepted whole entity
#: objects here, the v2 API takes strings.
_ID_LIKE_PARAMS = frozenset(
    [
        "id",
        "identifier",
        "perm_id",
        "code",
        "space",
        "project",
        "collection",
        "object",
        "parents",
        "children",
    ]
)

_MAGIC_RE = re.compile(r"^(?P<op>>=|>|<=|<|==|=)\s*(?P<value>.*)$")


def _looks_like_number(value: str) -> bool:
    try:
        float(value)
    except ValueError:
        return False
    return True


def _magic_to_filter(value: Any) -> Any:
    """Translate a 1.x magic-string operator value into a typed filter."""
    if not isinstance(value, str):
        return value
    match = _MAGIC_RE.match(value)
    if match is None:
        return value
    op, raw = match.group("op"), match.group("value")
    from .api import filters

    if _looks_like_number(raw):
        number: float | int = float(raw) if "." in raw else int(raw)
        return {
            ">": filters.gt,
            ">=": filters.gte,
            "<": filters.lt,
            "<=": filters.lte,
            "=": filters.number_eq,
            "==": filters.number_eq,
        }[op](number)
    if re.search(r"\d{4}-\d{2}-\d{2}", raw):
        if op in (">", ">="):
            return filters.date_after(raw)
        if op in ("<", "<="):
            return filters.date_before(raw)
        return filters.date_eq(raw)
    if op in ("=", "=="):
        return filters.eq(raw)
    warnings.warn(
        f"pybis 7: string ordering comparison {value!r} is not supported"
        f" anymore; matching the literal value instead.",
        UserWarning,
        stacklevel=4,
    )
    return filters.eq(value)


def _coerce_id_value(value: Any) -> Any:
    """Turn 1.x entity-object arguments into their identifying strings."""
    if isinstance(value, list):
        return [_coerce_id_value(item) for item in value]
    if isinstance(value, (str, bool, int)) or value is None:
        return value
    for attribute in ("identifier", "permId", "code"):
        ident = getattr(value, attribute, None)
        if isinstance(ident, str) and ident:
            return ident
    return value


def _translate_kwargs(old_name: str, kwargs: dict[str, Any]) -> dict[str, Any]:
    """Rename 1.x keyword arguments; hard-fail on removed parameters."""
    per_method = _PER_METHOD_PARAM_RENAMES.get(old_name, {})
    translated: dict[str, Any] = {}
    for key, value in kwargs.items():
        if key in per_method:
            new_key = per_method[key]
            if new_key is None:  # obsolete; behavior is built in now
                continue
            translated[new_key] = value
            continue
        if key in _VALUE_DEPENDENT:
            fetch_flag, relation_filter = _VALUE_DEPENDENT[key]
            if isinstance(value, bool):
                translated[fetch_flag] = value
            else:
                translated[relation_filter] = value
            continue
        if key in _REMOVED_PARAMS:
            raise TypeError(
                f"pybis 7: parameter {key!r} of {old_name}() was removed —"
                f" {_REMOVED_PARAMS[key]}. See MIGRATION_GUIDE.md."
            )
        translated[_PARAM_RENAMES.get(key, key)] = value
    return translated


def _adapt_for_new_signature(
    new_method: Callable[..., Any], translated: dict[str, Any]
) -> dict[str, Any]:
    """Fold 1.x free-form parts into the v2 signature.

    - ``where=`` dicts and unknown keyword arguments were property filters
      in 1.x; both merge into ``properties`` (magic strings become typed
      filters).
    - entity objects in identifying parameters become their identifier
      strings.
    """
    parameters = inspect.signature(new_method).parameters
    has_var_keyword = any(
        param.kind is inspect.Parameter.VAR_KEYWORD
        for param in parameters.values()
    )
    takes_properties = "properties" in parameters

    extra_properties: dict[str, Any] = {}
    if takes_properties and isinstance(translated.get("where"), dict):
        extra_properties.update(translated.pop("where"))

    for key in list(translated):
        if key not in parameters and not has_var_keyword:
            if takes_properties:
                extra_properties[key] = translated.pop(key)
            else:
                raise TypeError(
                    f"unexpected keyword argument {key!r}"
                    f" (see MIGRATION_GUIDE.md for renamed parameters)"
                )

    if extra_properties or isinstance(translated.get("properties"), dict):
        merged = dict(translated.get("properties") or {})
        merged.update(extra_properties)
        translated["properties"] = {
            code: _magic_to_filter(value) for code, value in merged.items()
        }

    for key in _ID_LIKE_PARAMS:
        if key in translated:
            translated[key] = _coerce_id_value(translated[key])
    return translated


def _make_shim(cls: type, old_name: str, new_name: str) -> Callable[..., Any]:
    """Build the deprecated shim delegating ``old_name`` to ``new_name``."""
    new_method = getattr(cls, new_name)  # docs/signature only; resolved live
    positional = _LEGACY_POSITIONAL.get(old_name, [])

    @functools.wraps(new_method)
    def shim(self: Any, *args: Any, **kwargs: Any) -> Any:
        warnings.warn(
            f"pybis 7: '{old_name}' is deprecated, use '{new_name}'."
            f" See MIGRATION_GUIDE.md.",
            DeprecationWarning,
            stacklevel=2,
        )
        if args:
            if len(args) > len(positional):
                raise TypeError(
                    f"{old_name}() takes at most {len(positional)} positional"
                    f" arguments ({len(args)} given)"
                )
            for name, value in zip(positional, args):
                kwargs.setdefault(name, value)
        translated = _translate_kwargs(old_name, kwargs)
        # 1.x used None for "no pagination limit"; drop those so the new
        # defaults apply. Filters explicitly passed as None are dropped too
        # (1.x signatures defaulted everything to None).
        for key in list(translated):
            if translated[key] is None:
                translated.pop(key)
        # resolve at call time so subclassing and test patching work
        target = getattr(self, new_name)
        translated = _adapt_for_new_signature(target, translated)
        # 1.x single-item getters accepted lists of identifiers
        first_param = next(iter(inspect.signature(target).parameters), None)
        if (
            new_name.startswith("get_")
            and first_param is not None
            and isinstance(translated.get(first_param), list)
        ):
            idents = translated.pop(first_param)
            return [target(ident, **translated) for ident in idents]
        return target(**translated)

    shim.__name__ = old_name
    shim.__qualname__ = f"{cls.__name__}.{old_name}"
    shim.__doc__ = f"Deprecated alias of :meth:`{new_name}` (pybis 1.x)."
    shim._pybis_compat_shim = True  # type: ignore[attr-defined]  # reason: shim marker
    return shim


def _make_param_shim(method: Callable[..., Any], name: str) -> Callable[..., Any]:
    """Wrap a same-name method whose 1.x parameters were renamed.

    Warns only when a legacy parameter (or legacy positional style) was
    actually used; otherwise the call passes through untouched.
    """
    positional = _PARAM_SHIMMED[name]
    new_params = inspect.signature(method).parameters
    param_names = [p for p in new_params if p != "self"]
    first_param = param_names[0] if param_names else None

    @functools.wraps(method)
    def shim(self: Any, *args: Any, **kwargs: Any) -> Any:
        legacy_keys = [
            key
            for key in kwargs
            if key not in new_params or key in _REMOVED_PARAMS
        ]
        legacy_positional = len(args) > 1  # v2 keeps at most the identifier
        if legacy_keys or legacy_positional:
            warnings.warn(
                f"pybis 7: {name}() parameters changed"
                f" ({', '.join(legacy_keys) or 'positional style'});"
                f" see MIGRATION_GUIDE.md.",
                DeprecationWarning,
                stacklevel=2,
            )
        for param, value in zip(positional, args):
            kwargs.setdefault(param, value)
        translated = _translate_kwargs(name, kwargs)
        for key in list(translated):
            if translated[key] is None:
                translated.pop(key)
        translated = _adapt_for_new_signature(method, translated)
        if (
            name.startswith("get_")
            and first_param is not None
            and isinstance(translated.get(first_param), list)
        ):
            idents = translated.pop(first_param)
            return [method(self, ident, **translated) for ident in idents]
        return method(self, **translated)

    shim._pybis_compat_shim = True  # type: ignore[attr-defined]  # reason: shim marker
    return shim


def install_compat(cls: type) -> None:
    """Install all deprecated method shims onto the Openbis class.

    Args:
        cls: The ``Openbis`` class.

    Raises:
        AssertionError: A rename entry conflicts with an existing attribute
            (the legacy method was not removed) or the new method is missing.
    """
    for old_name, new_name in _METHOD_RENAMES.items():
        assert hasattr(cls, new_name), f"missing new method {new_name}"
        existing = vars(cls).get(old_name)
        assert existing is None or getattr(
            existing, "_pybis_compat_shim", False
        ), (
            f"legacy method {old_name} still defined; remove it before"
            f" installing its shim"
        )
        setattr(cls, old_name, _make_shim(cls, old_name, new_name))

    for name in _PARAM_SHIMMED:
        method = getattr(cls, name, None)
        assert method is not None, f"missing method {name} for param shim"
        if getattr(method, "_pybis_compat_shim", False):
            continue  # already wrapped (idempotent re-install)
        setattr(cls, name, _make_param_shim(method, name))


__all__ = [
    "install_compat",
]
