#
#   Copyright ETH 2026 Zürich, Scientific IT Services
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
"""Deprecated pybis 1.x aliases, kept for one major release.

Every renamed method gets a shim here that emits a ``DeprecationWarning``
with a migration hint, translates renamed keyword arguments, and delegates
to the new method.  Removed implementation-detail parameters (``only_data``,
``raw_response``, ``use_cache``, ``attrs``) hard-fail with a pointed
``TypeError`` — silently ignoring them would change behavior invisibly.

This module is the only place where the 1.x vocabulary (sample, experiment)
may appear. See ``MIGRATION_GUIDE.md`` for the full mapping.
"""

from __future__ import annotations

import functools
import warnings
from typing import Any, Callable, TypeVar

C = TypeVar("C", bound=type)

#: camelCase (and old-vocabulary) keyword arguments → new snake_case names.
_PARAM_RENAMES: dict[str, str] = {
    "permId": "perm_id",
    "withParents": "with_parents",
    "withChildren": "with_children",
    "withAttachments": "with_attachments",
    "withDataSetIds": "with_dataset_ids",
    "projectId": "project_id",
    "userId": "user_id",
    "techId": "tech_id",
    "sessionName": "session_name",
    "validFrom": "valid_from",
    "validTo": "valid_to",
    "vocabularyCode": "vocabulary_code",
    "entityType": "entity_type",
    "propertyType": "property_type",
    "generatedCodePrefix": "generated_code_prefix",
    "subcodeUnique": "subcode_unique",
    "autoGeneratedCode": "auto_generated_code",
    "showContainer": "show_container",
    "showParents": "show_parents",
    "showParentMetadata": "show_parent_metadata",
    "validationPlugin": "validation_plugin",
    "mainDataSetPattern": "main_dataset_pattern",
    "mainDataSetPath": "main_dataset_path",
    "disallowDeletion": "disallow_deletion",
    "managedInternally": "managed_internally",
    "chosenFromList": "chosen_from_list",
    "dataType": "data_type",
    "sampleType": "object_type",
    "materialType": "material_type",
    "pluginType": "plugin_type",
    "userIds": "user_ids",
    "data_set_id": "dataset_id",
    # old vocabulary in parameter names
    "experiment": "collection",
    "sample": "object",
    "sample_ident": "identifier",
}

#: Implementation-detail parameters removed from the public API.
_REMOVED_PARAMS: dict[str, str] = {
    "only_data": (
        "entities are always returned; use entity.data for the raw dict"
    ),
    "raw_response": (
        "raw responses are no longer exposed; use the typed entities"
    ),
    "use_cache": "caching is transparent now; see Openbis.clear_cache()",
    "attrs": "use the returned entities (or result.df) instead",
}

#: Renamed methods: old name → new name. Grows wave by wave; every entry
#: must also appear in MIGRATION_GUIDE.md.
_METHOD_RENAMES: dict[str, str] = {
    "get_spaces": "search_spaces",
    "get_projects": "search_projects",
}

#: Positional parameter names of the legacy signatures, so positional 1.x
#: call styles keep working through the shims.
_LEGACY_POSITIONAL: dict[str, list[str]] = {
    "get_spaces": ["code", "start_with", "count"],
    "get_projects": ["space", "code", "start_with", "count"],
}


def _translate_kwargs(old_name: str, kwargs: dict[str, Any]) -> dict[str, Any]:
    """Rename 1.x keyword arguments; hard-fail on removed parameters."""
    translated: dict[str, Any] = {}
    for key, value in kwargs.items():
        if key in _REMOVED_PARAMS:
            raise TypeError(
                f"pybis 7: parameter {key!r} of {old_name}() was removed —"
                f" {_REMOVED_PARAMS[key]}. See MIGRATION_GUIDE.md."
            )
        translated[_PARAM_RENAMES.get(key, key)] = value
    return translated


def _make_shim(cls: type, old_name: str, new_name: str) -> Callable[..., Any]:
    """Build the deprecated shim delegating ``old_name`` to ``new_name``."""
    new_method = getattr(cls, new_name)  # docs/signature only; resolved live
    positional = _LEGACY_POSITIONAL.get(old_name, [])

    @functools.wraps(new_method)
    def shim(self: Any, *args: Any, **kwargs: Any) -> Any:
        warnings.warn(
            f"pybis 7: '{old_name}' is deprecated, use '{new_name}'."
            f" See MIGRATION_GUIDE.md.",
            DeprecationWarning,
            stacklevel=2,
        )
        if args:
            if len(args) > len(positional):
                raise TypeError(
                    f"{old_name}() takes at most {len(positional)} positional"
                    f" arguments ({len(args)} given)"
                )
            for name, value in zip(positional, args):
                kwargs.setdefault(name, value)
        translated = _translate_kwargs(old_name, kwargs)
        # 1.x used None for "no pagination limit"; drop those so the new
        # defaults apply.
        for pagination in ("count", "start_with"):
            if translated.get(pagination, 0) is None:
                translated.pop(pagination)
        # resolve at call time so subclassing and test patching work
        return getattr(self, new_name)(**translated)

    shim.__name__ = old_name
    shim.__qualname__ = f"{cls.__name__}.{old_name}"
    shim.__doc__ = f"Deprecated alias of :meth:`{new_name}` (pybis 1.x)."
    shim._pybis_compat_shim = True  # type: ignore[attr-defined]  # reason: shim marker
    return shim


def install_compat(cls: type) -> None:
    """Install all deprecated method shims onto the Openbis class.

    Args:
        cls: The ``Openbis`` class.

    Raises:
        AssertionError: A rename entry conflicts with an existing attribute
            (the legacy method was not removed) or the new method is missing.
    """
    for old_name, new_name in _METHOD_RENAMES.items():
        assert hasattr(cls, new_name), f"missing new method {new_name}"
        existing = vars(cls).get(old_name)
        assert existing is None or getattr(
            existing, "_pybis_compat_shim", False
        ), (
            f"legacy method {old_name} still defined; remove it before"
            f" installing its shim"
        )
        setattr(cls, old_name, _make_shim(cls, old_name, new_name))


__all__ = [
    "install_compat",
]
