#
#   Copyright ETH 2018 - 2026 Zürich, Scientific IT Services
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
"""Entity type and property type classes for openBIS.

Entity types define the *schema* of openBIS entities — which properties
are available, which are mandatory, how they are ordered, and which
validation plugins apply.

Key classes:
    - :class:`EntityType` — base logic shared by all entity types.
    - :class:`SampleType` — type definition for :class:`~pybis.sample.Sample` objects.
    - :class:`DataSetType` — type definition for :class:`~pybis.dataset.DataSet` objects.
    - :class:`ExperimentType` — type definition for :class:`~pybis.experiment.Experiment` objects.
    - :class:`MaterialType` — type definition for (deprecated) :class:`~pybis.material.Material`.
    - :class:`PropertyType` — standalone property type (reusable across entity types).
    - :class:`PropertyAssignment` — a property type assigned to an entity type.
"""

from __future__ import annotations

import copy
import sys
from typing import Any, Optional, TYPE_CHECKING

try:
    from warnings import deprecated  # Python 3.13+
except ImportError:
    import functools
    from warnings import warn

    def deprecated(msg: str):
        def decorator(cls):
            orig_init = cls.__init__

            @functools.wraps(orig_init)
            def __init__(self, *args, **kwargs):
                warn(msg, DeprecationWarning, stacklevel=2)
                orig_init(self, *args, **kwargs)

            cls.__init__ = __init__
            return cls

        return decorator


from pandas import DataFrame
from tabulate import tabulate

from .definitions import (
    get_method_for_entity,
    get_type_for_entity,
    get_definition_for_entity,
)
from .openbis_object import OpenBisObject
from .semantic_annotation import SemanticAnnotation
from .things import Things
from .utils import (
    format_timestamp,
    extract_code,
    extract_data_type,
    extract_name,
    VERBOSE,
    nvl,
)

if TYPE_CHECKING:
    from .pybis import Openbis
    from .openbis_object import OpenBisObject


class EntityType:
    """Base class providing schema-management methods for all openBIS entity types.

    This class is not used directly.  It is mixed into the concrete type
    classes (:class:`SampleType`, :class:`DataSetType`,
    :class:`ExperimentType`, :class:`MaterialType`) via multiple inheritance
    together with :class:`~pybis.openbis_object.OpenBisObject`.

    Key capabilities:

    - :meth:`get_property_assignments` — list all assigned properties.
    - :meth:`assign_property` / :meth:`revoke_property` — manage assignments.
    - :meth:`get_next_code` — generate the next code for new instances.

    Attributes:
        code (str): Unique type code (upper-case, e.g. ``"EXPERIMENTAL_STEP"``).
        description (str): Human-readable description.
        autoGeneratedCode (bool): Whether new instances get auto-generated codes.
        generatedCodePrefix (str): Prefix used for auto-generated codes.
    """

    def __init__(
        self,
        openbis_obj: Openbis,
        data: Optional[dict] = None,
        method: Optional[Any] = None,
        **kwargs: Any,
    ) -> None:
        """Initialise the EntityType mixin.

        Stores ``propertyAssignments`` from ``data`` and, optionally, a
        reference to the method used to re-fetch this type from openBIS.

        Args:
            openbis_obj: The :class:`~pybis.Openbis` connection instance.
            data: Raw entity-type dict from the V3 API.
            method: Callable to re-fetch this type (e.g.
                ``openbis.get_sample_type``).  Used after property assignment
                changes to refresh ``_propertyAssignments``.
            **kwargs: Forwarded to sub-class initialisers (ignored here).
        """
        self._set_entity_data(data)
        if method:
            self.__dict__["_get_method"] = method

    def _set_entity_data(self, data: Optional[dict] = None) -> None:
        """Extract and store ``propertyAssignments`` from a raw API response.

        Args:
            data: Raw entity-type dict.  If ``None`` or missing the key,
                ``_propertyAssignments`` is set to an empty list.
        """
        pas = []
        if data is not None and "propertyAssignments" in data:
            pas = data["propertyAssignments"]
        self.__dict__["_propertyAssignments"] = pas

    def __str__(self) -> str:
        return self.data["code"]

    def _attrs(self) -> list[str]:
        """Return the list of recognised entity-type attribute names.

        Returns:
            A list of attribute name strings.
        """
        return [
            "code",
            "description",
            "autoGeneratedCode",
            "subcodeUnique",
            "generatedCodePrefix",
            "listable",
            "showContainer",
            "showParents",
            "showParentMetadata",
            "validationPlugin",
            "managedInternally",
        ]

    def __dir__(self) -> list[str]:
        """Return the list of available attributes and methods for this entity type."""
        defs = get_definition_for_entity(self.entity)
        attrs = [
            "get_property_assignments()",
            "assign_property()",
            "revoke_property()",
            "move_property_to_top()",
            "move_property_after()",
            "get_validationPlugin()",
            "save()",
            "delete()",
            "get_next_sequence()",
            "get_next_code()",
        ]
        if self.is_new:
            return attrs + defs["attrs_new"]
        else:
            return attrs + list(set(defs["attrs"] + defs["attrs_up"]))

    def __getattr__(self, name: str) -> Any:
        """Return the value of an entity-type attribute."""
        if name in self._attrs():
            if name in self.data:
                return self.data[name]
            else:
                return ""

    def __eq__(self, other: Any) -> bool:
        """Compare entity types by their string representation (code)."""
        return str(self) == str(other)

    def __ne__(self, other: Any) -> bool:
        """Compare non-equal entity types by their string representation (code)."""
        return str(self) != str(other)

    def get_property_assignments(self) -> Things:
        """Return all property assignments for this entity type.

        Each assignment records which :class:`PropertyType` is attached,
        its data type, section, ordinal, mandatory flag, and other metadata.

        Returns:
            A :class:`~pybis.things.Things` container whose ``.df`` gives a
            :class:`~pandas.DataFrame` with columns ``code``, ``dataType``,
            ``section``, ``ordinal``, ``mandatory``,
            ``initialValueForExistingEntities``, ``showInEditView``,
            ``showRawValueInForms``, ``registrator``, ``registrationDate``,
            ``plugin``, ``unique``, ``pattern``, ``patternType``.

        Example:
            >>> sample_type.get_property_assignments().df
        """
        attrs = [
            "propertyType",
            "dataType",
            "section",
            "ordinal",
            "mandatory",
            "initialValueForExistingEntities",
            "showInEditView",
            "showRawValueInForms",
            "registrator",
            "registrationDate",
            "plugin",
            "unique",
            "pattern",
            "patternType",
        ]

        pas = self.__dict__["_propertyAssignments"]

        def create_data_frame(attrs: Any, props: Any, response: list) -> DataFrame:
            df = DataFrame(response, columns=attrs)

            if "dataType" in df:
                df["dataType"] = df["propertyType"].map(extract_data_type)

            if "propertyType" in df:
                df = df.rename(columns={"propertyType": "code"})
                df["code"] = df["code"].map(extract_code)

            if "plugin" in df:
                df["plugin"] = df["plugin"].map(extract_name)

            if "registrationDate" in df:
                df["registrationDate"] = df["registrationDate"].map(format_timestamp)

            return df

        def create_objects(response: list) -> list:
            result = []
            for element in response:
                obj = copy.deepcopy(element)
                obj["dataType"] = extract_data_type(obj["propertyType"])
                obj["code"] = extract_code(obj["propertyType"])
                obj["plugin"] = extract_name(obj["plugin"])
                obj["registrationDate"] = format_timestamp(obj["registrationDate"])
                result += [PropertyAssignment(openbis_obj=self.openbis, data=obj)]
            return result

        return Things(
            openbis_obj=self.openbis,
            entity="propertyType",
            single_item_method=self.openbis.get_property_type,
            identifier_name="propertyType",
            start_with=1,
            count=len(pas),
            totalCount=len(pas),
            response=pas,
            df_initializer=create_data_frame,
            objects_initializer=create_objects,
            attrs=attrs,
        )

    def assign_property(
        self,
        prop: Any,
        plugin: Optional[str] = None,
        section: Optional[str] = None,
        ordinal: Optional[int] = None,
        mandatory: bool = False,
        initialValueForExistingEntities: Optional[Any] = None,
        showInEditView: bool = True,
        showRawValueInForms: bool = True,
        unique: bool = False,
        patternType: Optional[str] = None,
        pattern: Optional[str] = None,
    ) -> None:
        """Assign a property type to this entity type.

        The entity type must already be saved.  If the property is already
        assigned, the call is silently ignored.

        Args:
            prop: A property type code string or a
                :class:`PropertyType` object.
            plugin: Optional validation plugin name to associate with this
                assignment.
            section: Section heading in the entity form.
            ordinal: Display order within the section (lower = earlier).
            mandatory: If ``True``, new instances must supply a value for
                this property before they can be saved.
            initialValueForExistingEntities: Default value applied to
                existing entities when a property is made mandatory after
                creation.
            showInEditView: Show this property in the edit form.
            showRawValueInForms: Show the raw stored value (not the label)
                in forms.
            unique: If ``True``, values must be unique across all instances
                of this entity type.
            patternType: Validation pattern type (e.g. ``"REGEX"``).
            pattern: Validation pattern string (used when ``patternType``
                is set).

        Raises:
            ValueError: If the entity type has not been saved yet.

        Example:
            >>> sample_type.assign_property("NAME", mandatory=True, section="Basic")
        """
        if self.is_new:
            raise ValueError(f"Please save {self.entity} first")

        if isinstance(prop, str):
            property_type = self.openbis.get_property_type(prop.upper())
        else:
            property_type = prop

        new_assignment = {
            "section": section,
            "ordinal": ordinal,
            "mandatory": mandatory,
            "initialValueForExistingEntities": initialValueForExistingEntities,
            "showInEditView": showInEditView,
            "showRawValueInForms": showRawValueInForms,
            "propertyTypeId": {
                "@type": "as.dto.property.id.PropertyTypePermId",
                "permId": property_type.permId,
            },
            "@type": "as.dto.property.create.PropertyAssignmentCreation",
            "unique": unique,
        }

        if patternType is not None:
            new_assignment["patternType"] = patternType
            new_assignment["pattern"] = pattern

        if plugin is not None:
            plugin_obj = self.openbis.get_plugin(plugin)
            new_assignment["pluginId"] = {
                "@type": "as.dto.plugin.id.PluginPermId",
                "permId": plugin_obj.permId,
            }

        request = self._get_request_for_pa(new_assignment, "Add")
        try:
            self.openbis._post_request(self.openbis.as_v3, request)
        except ValueError as exc:
            if "already assigned" in str(exc):
                if VERBOSE:
                    print(
                        f"Property {property_type.permId} already assigned to {self.permId}"
                    )
                return
            else:
                raise ValueError(exc)

        new_data = self._get_method(self.permId, only_data=True)
        self._set_entity_data(new_data)
        if VERBOSE:
            print(f"Property {property_type.permId} assigned to {self.permId}")

    def revoke_property(self, prop: Any, force: bool = False) -> None:
        """Remove a property assignment from this entity type.

        Args:
            prop: A property type code string or a :class:`PropertyType`
                object.
            force: If ``True``, revoke the property even when existing
                entities still carry values for it.  Use with care — data
                may be lost.

        Example:
            >>> sample_type.revoke_property("OBSOLETE_PROP", force=True)
        """
        if isinstance(prop, str):
            property_type = prop.upper()
        else:
            property_type = prop.permId.upper()

        items = {
            "entityTypeId": self._permId,
            "propertyTypeId": {
                "permId": property_type,
                "@type": "as.dto.property.id.PropertyTypePermId",
            },
            "@type": "as.dto.property.id.PropertyAssignmentPermId",
        }
        request = self._get_request_for_pa(items, "Remove", force)
        resp = self.openbis._post_request(self.openbis.as_v3, request)
        if not resp:
            new_data = self._get_method(self.permId, only_data=True)
            self._set_entity_data(new_data)
            if VERBOSE:
                print(f"Property {property_type} revoked from {self.permId}")

    def _get_request_for_pa(
        self, items: dict, item_action: str, force: bool = False
    ) -> dict:
        """Build a V3 API request to add or remove a property assignment.

        Args:
            items: The assignment or assignment-id dict to include in the
                request.
            item_action: ``"Add"`` or ``"Remove"``.
            force: Forwarded to ``forceRemovingAssignments`` when removing.

        Returns:
            A complete V3 API request dict.
        """
        method = get_method_for_entity(self.entity, "update")
        entity_type = get_type_for_entity(self.entity, "update")

        list_action_type = "as.dto.common.update.ListUpdateAction" + item_action

        request = {
            "method": method,
            "params": [
                self.openbis.token,
                [
                    {
                        "propertyAssignments": {
                            "actions": [
                                {
                                    "items": [
                                        {
                                            **items,
                                        }
                                    ],
                                    "@type": list_action_type,
                                }
                            ],
                            "@type": "as.dto.entitytype.update.PropertyAssignmentListUpdateValue",
                            "forceRemovingAssignments": force,
                        },
                        **entity_type,
                        "typeId": self._permId,
                    }
                ],
            ],
        }

        return request

    def move_property_to_top(self, property: Any) -> None:
        """Move a property assignment to the top of the list.

        Raises:
            NotImplementedError: Always — not yet implemented.
        """
        raise NotImplementedError("Not yet implemented.")

    def move_property_after(self, property: Any, after_property: Any) -> None:
        """Move a property assignment to appear after another.

        Raises:
            NotImplementedError: Always — not yet implemented.
        """
        raise NotImplementedError("Not yet implemented.")

    @property
    def get_validationPlugin(self) -> Optional[Any]:
        """Return the validation plugin assigned to this type, or ``None``.

        Returns:
            The plugin object if a validation plugin is configured, or
            ``None`` when none is set.
        """
        try:
            return self.openbis.get_plugin(self._validationPlugin["name"])
        except Exception:
            pass

    def codes(self) -> list[str]:
        """Return the lower-cased property codes for this entity type.

        Returns:
            A list of property code strings (lower-case).
        """
        codes = []
        for pa in self.data["propertyAssignments"]:
            codes.append(pa["propertyType"]["code"].lower())
        return codes

    def get_next_sequence(self) -> Optional[int]:
        """Query the ELN custom service for the next auto-increment sequence number.

        Returns:
            The next sequence integer, or ``None`` if the service is
            unavailable or this type does not use sequences.
        """
        request = {
            "method": "executeCustomASService",
            "params": [
                self.openbis.token,
                {
                    "permId": "as-eln-lims-api",
                    "@type": "as.dto.service.id.CustomASServiceCode",
                },
                {
                    "parameters": {
                        "method": "getNextSequenceForType",
                        "sampleTypeCode": self.code,
                    },
                    "@type": "as.dto.service.CustomASServiceExecutionOptions",
                },
            ],
        }

        try:
            resp = self.openbis._post_request(self.openbis.as_v3, request)
        except Exception:
            return None
        return resp

    def get_next_code(self) -> str:
        """Return the next auto-generated code for a new instance of this type.

        Combines :meth:`get_next_sequence` with :attr:`generatedCodePrefix`.

        Returns:
            A code string such as ``"EXP42"`` for a type whose prefix is
            ``"EXP"`` and whose current sequence is ``42``.

        Raises:
            ValueError: If the sequence number could not be obtained.

        Example:
            >>> code = sample_type.get_next_code()
            >>> sample = openbis.new_sample(type=sample_type, code=code)
        """
        seq = self.get_next_sequence()
        if seq:
            return self.generatedCodePrefix + str(seq)
        else:
            raise ValueError("Could not generate next code.")


class SampleType(
    OpenBisObject,
    EntityType,
    entity="sampleType",
    single_item_method_name="get_object_type",
):
    """Schema definition for :class:`~pybis.sample.Sample` objects.

    Fetch via ``openbis.get_sample_type()`` / ``openbis.get_sample_types()``
    and create new types with ``openbis.new_sample_type()``.

    In addition to the :class:`EntityType` methods, sample types support
    :meth:`add_semantic_annotation` and :meth:`get_semantic_annotations`
    for ontology integration.

    Example:
        >>> st = openbis.get_sample_type("EXPERIMENTAL_STEP")
        >>> st.get_property_assignments().df
        >>> st.assign_property("DESCRIPTION", section="General")
    """

    def __init__(
        self,
        openbis_obj: Any,
        type: Optional[Any] = None,
        data: Optional[dict] = None,
        props: Optional[Any] = None,
        method: Optional[Any] = None,
        **kwargs: Any,
    ) -> None:
        OpenBisObject.__init__(
            self, openbis_obj, type=type, data=data, props=props, **kwargs
        )
        EntityType.__init__(
            self,
            openbis_obj,
            type=type,
            data=data,
            props=props,
            method=method,
            **kwargs,
        )

    def __dir__(self) -> list[str]:
        return (
            ["add_semantic_annotation()", "get_semantic_annotations()"]
            + EntityType.__dir__(self)
            + OpenBisObject.__dir__(self)
        )

    def add_semantic_annotation(self, **kwargs: Any) -> SemanticAnnotation:
        """Create and save a semantic annotation for this sample type.

        Args:
            **kwargs: Annotation fields forwarded to
                :class:`~pybis.semantic_annotation.SemanticAnnotation`.
                Typical keys: ``predicateOntologyId``,
                ``predicateAccessionId``, ``descriptorOntologyId``,
                ``descriptorAccessionId``.

        Returns:
            The newly created :class:`~pybis.semantic_annotation.SemanticAnnotation`.

        Example:
            >>> st.add_semantic_annotation(
            ...     predicateOntologyId="ro",
            ...     predicateAccessionId="RO:0000056",
            ... )
        """
        semantic_annotation = SemanticAnnotation(
            openbis_obj=self.openbis, isNew=True, entityType=self.code, **kwargs
        )
        semantic_annotation.save()
        return semantic_annotation

    def get_semantic_annotations(self) -> Things:
        """Return all semantic annotations for this sample type.

        Returns:
            A :class:`~pybis.things.Things` container of
            :class:`~pybis.semantic_annotation.SemanticAnnotation` objects.

        Example:
            >>> st.get_semantic_annotations().df
        """
        return self.openbis.search_semantic_annotations(entityType=self.code)


class DataSetType(
    OpenBisObject,
    EntityType,
    entity="dataSetType",
    single_item_method_name="get_dataset_type",
):
    """Schema definition for :class:`~pybis.dataset.DataSet` objects.

    Fetch via ``openbis.get_dataset_type()`` / ``openbis.get_dataset_types()``
    and create new types with ``openbis.new_dataset_type()``.

    Example:
        >>> dt = openbis.get_dataset_type("RAW_DATA")
        >>> dt.get_property_assignments().df
    """

    def __init__(
        self,
        openbis_obj: Any,
        type: Optional[Any] = None,
        data: Optional[dict] = None,
        props: Optional[Any] = None,
        method: Optional[Any] = None,
        **kwargs: Any,
    ) -> None:
        OpenBisObject.__init__(
            self, openbis_obj, type=type, data=data, props=props, **kwargs
        )
        EntityType.__init__(
            self,
            openbis_obj,
            type=type,
            data=data,
            props=props,
            method=method,
            **kwargs,
        )

    def __dir__(self) -> list[str]:
        return [] + EntityType.__dir__(self) + OpenBisObject.__dir__(self)


@deprecated(
    "The Material concept is deprecated in openBIS. Prefer SampleType for new entity types."
)
class MaterialType(
    OpenBisObject,
    EntityType,
    entity="materialType",
    single_item_method_name="get_material_type",
):
    """Schema definition for (deprecated) :class:`~pybis.material.Material` objects.

    .. deprecated::
        The Material concept is deprecated in openBIS.  Prefer
        :class:`SampleType` for new entity types.
    """

    def __init__(
        self,
        openbis_obj: Any,
        type: Optional[Any] = None,
        data: Optional[dict] = None,
        props: Optional[Any] = None,
        method: Optional[Any] = None,
        **kwargs: Any,
    ) -> None:
        OpenBisObject.__init__(
            self, openbis_obj, type=type, data=data, props=props, **kwargs
        )
        EntityType.__init__(
            self,
            openbis_obj,
            type=type,
            data=data,
            props=props,
            method=method,
            **kwargs,
        )

    def __dir__(self) -> list[str]:
        return [] + EntityType.__dir__(self) + OpenBisObject.__dir__(self)


class ExperimentType(
    OpenBisObject,
    EntityType,
    entity="experimentType",
    single_item_method_name="get_collection_type",
):
    """Schema definition for :class:`~pybis.experiment.Experiment` objects.

    Fetch via ``openbis.get_experiment_type()`` /
    ``openbis.get_experiment_types()`` and create new types with
    ``openbis.new_experiment_type()``.

    Example:
        >>> et = openbis.get_experiment_type("DEFAULT_EXPERIMENT")
        >>> et.get_property_assignments().df
    """

    def __init__(
        self,
        openbis_obj: Any,
        type: Optional[Any] = None,
        data: Optional[dict] = None,
        props: Optional[Any] = None,
        method: Optional[Any] = None,
        **kwargs: Any,
    ) -> None:
        OpenBisObject.__init__(
            self, openbis_obj, type=type, data=data, props=props, **kwargs
        )
        EntityType.__init__(
            self,
            openbis_obj,
            type=type,
            data=data,
            props=props,
            method=method,
            **kwargs,
        )

    def __dir__(self) -> list[str]:
        return [] + EntityType.__dir__(self) + OpenBisObject.__dir__(self)


class PropertyType(
    OpenBisObject, entity="propertyType", single_item_method_name="get_property_type"
):
    """A reusable property type that can be assigned to multiple entity types.

    Property types define the *data type*, label, and other metadata for a
    single property.  They are shared across entity types — one
    ``DESCRIPTION`` property type can be assigned to both ``EXPERIMENTAL_STEP``
    and ``MATERIAL_X``.

    Fetch via ``openbis.get_property_type()`` /
    ``openbis.get_property_types()`` and create new types with
    ``openbis.new_property_type()``.

    Attributes:
        code (str): Unique property type code.
        label (str): Human-readable label shown in forms.
        description (str): Long description of what this property captures.
        dataType (str): One of the values in
            :data:`~pybis.openbis_typing.PropertyDataType`.
        vocabulary (Optional[str]): Vocabulary code for
            ``CONTROLLEDVOCABULARY`` properties.
        schema (Optional[str]): XML schema for ``XML`` properties.

    Example:
        >>> pt = openbis.new_property_type(
        ...     code="CONCENTRATION",
        ...     label="Concentration",
        ...     description="Concentration in µM",
        ...     dataType="REAL",
        ... )
        >>> pt.save()
        >>> sample_type.assign_property(pt, mandatory=False)
    """

    def save(self) -> OpenbisObject:
        """Persist this property type to openBIS (create or update).

        For **new** property types, checks that no type with the same code
        already exists before calling the V3 API.

        Raises:
            ValueError: If a property type with the same code already exists.
        """
        if self.is_new:
            get_single_item = self._get_single_item_method()
            try:
                new_entity_data = get_single_item(self.code)
                raise ValueError(f"propertyType '{self.code}' already exists!")
            except ValueError as e:
                if not "no such propertyType" in str(e):
                    raise e
        super().save()


class PropertyAssignment:
    """A property type assignment linking a :class:`PropertyType` to an entity type.

    :class:`PropertyAssignment` objects are returned by
    :meth:`EntityType.get_property_assignments`.  They record the assignment
    metadata such as the section, ordinal, mandatory flag, and validation
    plugin for a single property within a specific entity type.

    Attributes:
        code (str): Lower-cased property type code.
        dataType (str): Data type of the property.
        section (Optional[str]): Form section heading.
        ordinal (int): Display order within the section.
        mandatory (bool): Whether the property must be filled.
        initialValueForExistingEntities (Any): Default value for existing entities
            when a property is made mandatory retroactively.
        showInEditView (bool): Whether to show in the edit form.
        showRawValueInForms (bool): Whether to show the raw value.
        registrator (str): User who created the assignment.
        registrationDate (str): ISO-8601 creation timestamp.
        plugin (Optional[str]): Name of the validation plugin, if any.
        unique (bool): Whether values must be unique across instances.
        pattern (Optional[str]): Validation pattern string.
        patternType (Optional[str]): Validation pattern type.
    """

    openbis: Any
    data: Optional[dict[str, Any]]

    def __init__(
        self, openbis_obj: Any, data: Optional[dict] = None, **kwargs: Any
    ) -> None:
        """Initialise a PropertyAssignment from a pre-processed data dict.

        Args:
            openbis_obj: The :class:`~pybis.Openbis` connection instance.
            data: Pre-processed assignment dict (code, dataType, etc. already
                extracted from the raw API response).
            **kwargs: Ignored.
        """
        self.openbis = openbis_obj
        self.data = data

    def __getattr__(self, name: str) -> Any:
        if name in self._attrs():
            if name in self.data:
                return self.data[name]
            else:
                return ""

    def __repr__(self) -> str:
        headers = ["attribute", "value"]
        lines = []
        for attr in self._attrs():
            lines.append([attr, nvl(getattr(self, attr, ""))])

        return tabulate(lines, headers=headers)

    def get_property_type(self) -> "PropertyType":
        """Fetch the full :class:`PropertyType` object for this assignment.

        Returns:
            The :class:`PropertyType` corresponding to this assignment's code.

        Example:
            >>> pa = sample_type.get_property_assignments()[0]
            >>> pt = pa.get_property_type()
            >>> print(pt.dataType)
            REAL
        """
        return self.openbis.get_property_type(self.data["propertyType"]["code"])

    def _attrs(self) -> list[str]:
        """Return the list of recognised attribute names.

        Returns:
            A list of attribute name strings.
        """
        return [
            "code",
            "dataType",
            "section",
            "ordinal",
            "mandatory",
            "initialValueForExistingEntities",
            "showInEditView",
            "showRawValueInForms",
            "registrator",
            "registrationDate",
            "plugin",
            "unique",
            "pattern",
            "patternType",
        ]
