label = ${eln-lims.as.services.exports-api.label:Exports API}
class = ch.ethz.sis.openbis.generic.server.asapi.v3.helper.service.JythonBasedCustomASServiceExecutor
script-path = ${eln-lims.as.services.exports-api.script-path:exportFacade.py}
limit-data-size-megabytes = ${eln-lims.as.services.exports-api.limit-data-size-megabytes:10000}
share-id = ${eln-lims.as.services.exports-api.share-id:}

# Zenodo export config
#zenodo.url=${zenodo-exports-api-zenodoUrl:https://sandbox.zenodo.org/}
zenodo.url=${zenodo-exports-api-zenodoUrl:https://zenodo.org/}
zenodo.http.proxy.url=${zenodo-exports-api-http-proxy-url:}
zenodo.http.proxy.port=${zenodo-exports-api-http-proxy-port:}

# Research Collection export config
research_collection.enabled=${eln-lims.as.services.exports-api.research_collection.enabled:false}
research_collection.realm=${eln-lims.as.services.exports-api.research_collection.realm:SWORD2}
research_collection.limit-data-size-megabytes=${rc-exports-api-limit-data-size-megabytes:10000}
research_collection.service-document-url=${rc-exports-api-service-document-url:https://test.research-collection.ethz.ch/swordv2/servicedocument}
research_collection.http.proxy.url=${rc-exports-api-http-proxy-url:}
research_collection.http.proxy.port=${rc-exports-api-http-proxy-port:}
research_collection.user=${rc-exports-api-user}
research_collection.password=${rc-exports-api-password}

# SciCat export config
sci-cat.enabled=${eln-lims.as.services.exports-api.sci-cat.enabled:false}
sci-cat.url=${eln-lims.as.services.exports-api.sci-cat.url:https://discovery.development.psi.ch/}
sci-cat.http.proxy.url=${eln-lims.as.services.exports-api.sci-cat.http.proxy.url:}
sci-cat.http.proxy.port=${eln-lims.as.services.exports-api.sci-cat.http.proxy.port:}

# RO-Crate export config
ro-crate.url=${eln-lims.as.services.exports-api.ro-crate.url:http://localhost:8086/openbis/open-api/ro-crate}