label = ${eln-lims.as.services.exports-api.label:Exports API}
class = ch.ethz.sis.openbis.generic.server.asapi.v3.helper.service.JythonBasedCustomASServiceExecutor
script-path = ${eln-lims.as.services.exports-api.script-path:exportFacade.py}
limit-data-size-megabytes = ${eln-lims.as.services.exports-api.limit-data-size-megabytes:10000}
share-id = ${eln-lims.as.services.exports-api.share-id:}
