import org.gradle.api.tasks.bundling.Jar

evaluationDependsOn(':lib-commonbase')
evaluationDependsOn(':lib-common')
evaluationDependsOn(':api-openbis-java')
evaluationDependsOn(':api-openbis-javascript')
evaluationDependsOn(':api-data-store-server-javascript')
evaluationDependsOn(':api-data-store-server-java')
evaluationDependsOn(':lib-openbis-common')
evaluationDependsOn(':lib-authentication')
evaluationDependsOn(':lib-dbmigration')

apply from: '../build/javaproject.gradle'

configurations.create('testRuntimeFirst')
configurations.create('devRuntime')
configurations.create('asExecRuntime')

dependencies {
    api project(':lib-common'),
            project(':api-openbis-java'),
            project(':lib-openbis-commonbase'),
            project(':lib-openbis-common'),
            project(':lib-openbis-messages'),
            project(':lib-authentication'),
            project(':lib-mail'),
            project(':lib-json'),
            project(':lib-maintenance'),
            project(':lib-dbmigration'),
            project(':lib-messages-db'),
            project(':lib-two-phase-transaction'),
            project(':api-data-store-server-java'),
            project(':api-data-store-server-javascript'),
            libs.sencha.gxt,
            libs.org.javassist.javassist,
            libs.org.hibernate.orm.hibernate.core,
            libs.org.glassfish.jakarta.el,
            libs.com.fasterxml.classmate,
            libs.org.eclipse.jetty.jetty.deploy,
            libs.jakarta.activation.jakarta.activation.api,
            libs.jakarta.servlet.jakarta.servlet.api.v60,
            libs.jakarta.validation.jakarta.validation.api,
            libs.jakarta.annotation.jakarta.annotation.api,
            libs.com.sun.mail.javax.mail,
            libs.org.springframework.spring.orm,
            libs.cisd.cisd.hotdeploy,
            libs.org.apache.poi.poi.ooxml,
            libs.org.hibernate.validator.hibernate.validator,
            libs.it.unimi.dsi.fastutil,
            libs.org.apache.commons.commons.collections4,
            libs.org.apache.commons.commons.compress,
            libs.org.springframework.spring.context.support,
            libs.org.springframework.spring.expression,
            //'ehcache:ehcache:2.10.0',
            libs.jline.jline,
            libs.org.jsoup.jsoup,
            libs.org.apache.pdfbox.pdfbox,
            libs.org.apache.pdfbox.fontbox,
            libs.org.apache.pdfbox.xmpbox,
            libs.de.rototor.pdfbox.graphics2d,
//            'org.apache.pdfbox:pdfbox-io:3.0.0',
//            'de.rototor.pdfbox:graphics2d:3.0.0',
            libs.com.openhtmltopdf.openhtmltopdf.core,
            libs.com.openhtmltopdf.openhtmltopdf.pdfbox,
            libs.org.eclipse.jetty.jetty.server,
            libs.org.eclipse.jetty.ee.jetty.ee.webapp,
            libs.org.eclipse.jetty.ee10.jetty.ee10.webapp,
            libs.org.eclipse.jetty.ee10.jetty.ee10.servlet,
            libs.org.eclipse.jetty.jetty.security,
            libs.org.eclipse.jetty.jetty.session,
            libs.org.eclipse.jetty.jetty.deploy,
            libs.org.eclipse.jetty.ee10.jetty.ee10.annotations,
            libs.org.eclipse.jetty.ee10.jetty.ee10.plus,
            libs.org.eclipse.jetty.ee10.jetty.ee10.jndi,
            libs.org.eclipse.jetty.jetty.jndi,
            libs.org.eclipse.jetty.jetty.xml,
            libs.org.eclipse.jetty.jetty.plus,
            libs.org.eclipse.jetty.compression.jetty.compression.common,
            libs.org.eclipse.jetty.compression.jetty.compression.gzip,
            libs.org.eclipse.jetty.jetty.annotations,
            libs.org.aspectj.aspectjweaver.v18,
            libs.org.slf4j.slf4j.api

    implementation libs.javax.cache.cache.api
    implementation(libs.org.ehcache.ehcache) {
        artifact {
            classifier = "jakarta"
            type = "jar"
        }
    }
//            {
//        capabilities {
//            requireCapability('org.ehcache:ehcache-jakarta')
//        }
//    }


    runtimeOnly libs.org.slf4j.slf4j.jdk14,
            libs.jakarta.transaction.jakarta.transaction.api
    runtimeOnly(libs.org.apache.commons.commons.fileupload2.jakarta.servlet5){
        exclude group:'org.junit'
    }

    asExecRuntime files("../core-plugin-openbis/dist/core-plugins/eln-lims-imaging-core/src/as/api-listener/imaging-dataset-interceptor/lib/imaging-dataset-interceptor.jar"),
            files("../core-plugin-openbis/dist/core-plugins/eln-lims-imaging-core/src/as/services/imaging/lib/openBIS-imaging-technology.jar"),
            files("../core-plugin-openbis/dist/core-plugins/eln-lims-imaging-nanonis-adapter/src/as/services/imaging-nanonis/lib/premise-adapters.jar"),
            files("../core-plugin-openbis/dist/core-plugins/eln-lims-imaging-test-adapter/src/as/services/imaging-test/lib/imaging-test-adapters.jar"),
            // zenodo export dependencies
            files("../ui-eln-lims/src/core-plugins/eln-lims/1/as/services/exports-api/lib/job-scheduler.jar"),
            files("../ui-eln-lims/src/core-plugins/eln-lims/1/as/services/exports-api/lib/json-20250517.jar")

    testImplementation project(path: ':lib-commonbase', configuration: 'tests'),
            project(path: ':lib-common', configuration: 'tests'),
            project(path: ':lib-dbmigration', configuration: 'tests'),
            project(path: ':lib-authentication', configuration: 'tests'),
            project(path: ':api-openbis-java', configuration: 'tests'),
            project(path: ':lib-openbis-common', configuration: 'tests'),
            project(path: ':lib-openbis-commonbase', configuration: 'tests'),
            project(path: ':lib-two-phase-transaction', configuration: 'tests'),
            project(path: ':api-data-store-server-javascript', configuration: 'tests'),
            libs.org.aspectj.aspectjweaver,
            libs.org.aspectj.aspectjrt,
            libs.fjelmer.classycle,
            libs.org.testng.testng,
            libs.org.junit.junit,
            libs.org.jmock.jmock,
            libs.org.springframework.spring.test,
            libs.org.apache.commons.commons.fileupload2.jakarta.servlet5,
            libs.org.hamcrest.hamcrest.integration,
            libs.org.hamcrest.hamcrest.library

    testRuntimeFirst libs.jakarta.servlet.jakarta.servlet.api

}

sourceSets.test.runtimeClasspath = configurations.testRuntimeFirst + sourceSets.test.runtimeClasspath


sourceSets {
    main {
        resources {
            srcDirs = ['source/java']
        }
    }
    test {
        resources {
            srcDirs = ['sourceTest/java']
        }
    }

    asExec {
        java {
            srcDirs = ['source/java']
        }
        resources {
            srcDirs = ['source/java']
        }

        compileClasspath += sourceSets.main.compileClasspath
        runtimeClasspath += sourceSets.main.runtimeClasspath + configurations.asExecRuntime + configurations.devRuntime
    }
}

task cleanDbSuite(type: Test) {
    useTestNG()
    systemProperty "ant.project.name", project.name
    maxHeapSize = "4096m"
    jvmArgs += [
            '-Duser.timezone=Europe/Zurich',
            '-Djava.util.logging.config.file=' + file('etc/jullogging.properties').absolutePath]
    testLogging.showStandardStreams = true
    ignoreFailures = true

    options.suites('sourceTest/java/tests_system_cleandb_excluding_authorization.xml')
    reports.html.destination = file("${project.buildDir}/reports/tests-cleandb")
}

task cleanDbSuiteProjectSamplesEnabled(type: Test) {
    useTestNG()
    systemProperty "ant.project.name", project.name
    maxHeapSize = "4096m"
    jvmArgs += [
            '-Duser.timezone=Europe/Zurich',
            '-Djava.util.logging.config.file=' + file('etc/jullogging.properties').absolutePath]
    testLogging.showStandardStreams = true
    ignoreFailures = true
    systemProperty "project-samples-enabled", 'true'

    options.suites('sourceTest/java/tests_system_cleandb_excluding_authorization_project_samples.xml')
    reports.html.destination = file("${project.buildDir}/reports/tests-cleandb-project-samples")
}

task testProjectSamplesEnabled(type: Test) {
    useTestNG()
    systemProperty "ant.project.name", project.name
    maxHeapSize = "4096m"
    jvmArgs += [
            '-Duser.timezone=Europe/Zurich',
            '-Djava.util.logging.config.file=' + file('etc/jullogging.properties').absolutePath]
    testLogging.showStandardStreams = true
    ignoreFailures = true
    systemProperty "project-samples-enabled", 'true'

    options.suites('sourceTest/java/tests_project_samples.xml')
    reports.html.destination = file("${project.buildDir}/reports/tests-project-samples")
}

// This task is here to make WebAppsPropertiesTest to work. It requires some data files
// to be present on the same directory than the class file itself.
task copyTestData(type: Copy, dependsOn: testClasses) {
    from "${project.projectDir}/sourceTest/java/ch/systemsx/cisd/openbis/generic/shared/basic"
    into "${project.buildDir}/classes/test/ch/systemsx/cisd/openbis/generic/shared/basic"
    include "*.properties"
}

task openBISDevelopmentEnvironmentASStart(type: JavaExec) {
    mainClass = 'ch.ethz.sis.openbis.generic.server.dev.EmbeddedJettyDevelopmentServer'
    classpath = sourceSets.asExec.runtimeClasspath
    jvmArgs(['-Dpython.path=../libraries/jython/jython-lib',
             '-Das.logging.configuration=etc/logging.properties',
             '-Djavax.net.ssl.trustStore=dist/server/openBIS.keystore',
             // config for imaging
             '-Deln-lims-imaging-core.as.services.imaging.storageRoot.dss=../server-original-data-store/targets/store',
             '-Deln-lims-imaging-core.as.services.imaging.storageRoot.afs=../server-data-store/targets/tests/storage',

             '-Dorg.mortbay.util.FileResource.checkAliases=false',
             '--add-opens=java.base/java.util=ALL-UNNAMED', '--add-opens=java.base/java.lang=ALL-UNNAMED',
             '-Xmx4096M', '-ea'])
    args(['--classes', '../lib-commonbase/targets/gradle/classes/java/main',
          '--classes', '../lib-common/targets/gradle/classes/java/main',
          '--classes', '../lib-authentication/targets/gradle/classes/java/main',
          '--classes', '../lib-dbmigration/targets/gradle/classes/java/main',
          '--classes', '../lib-openbis-common/targets/gradle/classes/java/main',
          '--classes', '../api-openbis-java/targets/gradle/classes/java/main',
          '--classes', 'targets/gradle/classes/java/main', '--lib', 'targets/www/lib/', '--port', '8888', 'targets/www'])
}


/////////// AS JAVADOC ////////////////////

tasks.register('serverApplicationServerJavadoc', Javadoc) {
    mustRunAfter ":core-plugin-openbis:copyOpenbisNgUiToCorePlugins"
    source project.files('source/java').getAsFileTree().matching {
        include "**/ch/systemsx/cisd/openbis/generic/server/jython/api/v1/**/*.java"
        include "**/ch/systemsx/cisd/openbis/generic/shared/managed_property/api/**/*.java"
    }
    classpath = sourceSets.asExec.runtimeClasspath
    destinationDir = file("$buildDir/docs/javadoc-server-application-server")
}

tasks.register('serverApplicationServerJavadocZip', Zip) {
    dependsOn serverApplicationServerJavadoc
    archiveBaseName = 'openbis-application-server-javadoc'
    from serverApplicationServerJavadoc.destinationDir
}

tasks.register('javadocTar', Tar) {
    compression = Compression.GZIP
    dependsOn serverApplicationServerJavadoc
    archiveFileName = "openbis-original-data-store-javadoc-${version}.tar.gz"
    from serverApplicationServerJavadoc.destinationDir
}



/////////// DYNAMIC PROPERTIES API ////////////////////


task dynamicApiJavadoc(type: Javadoc) {
    mustRunAfter ":core-plugin-openbis:copyOpenbisNgUiToCorePlugins"
    source project.files('source/java').getAsFileTree().matching {
        include "ch/systemsx/cisd/openbis/generic/shared/hotdeploy_plugins/api/*.java"
    }
    classpath = sourceSets.asExec.runtimeClasspath
    destinationDir = file("$buildDir/docs/javadoc-dynamic-api")
}

tasks.register('dynamicApiJavadocZip', Zip) {
    dependsOn dynamicApiJavadoc
    archiveBaseName = 'dynamic-api-javadoc'
    from dynamicApiJavadoc.destinationDir
}

tasks.register('dynamicApiJavadocTar', Tar) {
    compression = Compression.GZIP
    dependsOn dynamicApiJavadoc
    archiveFileName = "dynamic-api-javadoc-${version}.tar.gz"
    from dynamicApiJavadoc.destinationDir
}

testProjectSamplesEnabled.dependsOn(copyTestData)
cleanDbSuiteProjectSamplesEnabled.dependsOn(testProjectSamplesEnabled)

test.maxHeapSize = "10240m"
test.jvmArgs += [
        '-Duser.timezone=Europe/Zurich',
        '-Djava.util.logging.config.file=etc/jullogging.properties']
test.dependsOn(copyTestData)
test.dependsOn(cleanDbSuite)

task runOnlyOneTestSuite(type: Test) {
    // Dedicated task to run only the DB TestNG suite.
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
    environment.remove("DISPLAY")
    useTestNG {
        suites 'sourceTest/java/tests_system_test_one.xml'
    }
    systemProperty "ant.project.name", project.name
    maxHeapSize = "10240m"
    jvmArgs += [
            '-Duser.timezone=Europe/Zurich',
            '-Djava.util.logging.config.file=etc/jullogging.properties',
            '-Dorg.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StrErrLog',
            "--add-opens", "java.base/java.lang=ALL-UNNAMED",
            "--add-opens", "java.base/java.lang.reflect=ALL-UNNAMED",
            "--add-opens", "java.base/java.io=ALL-UNNAMED"
    ]
    testLogging.showStandardStreams = true
    ignoreFailures = true
    dependsOn(testClasses, copyTestData)
}

apply from: 'elndev.gradle'

//
// Version Management
//

def execute_working_dir(command, arguments, working_dir) {
    new ByteArrayOutputStream().withStream { os ->
        print "execute: ${command}"
        arguments.collect({print " ${it}"})
        println ''
        def result = exec {
            executable = command
            args = arguments
            standardOutput = os
        }
        return os.toString().split('\n')
    }
}

def isGitProject() {
    return new java.io.File(projectDir, ".git").isDirectory() || new java.io.File(projectDir, "../.git").isDirectory()
}

def calculateBuildInfo() {
    if (isGitProject()) {
        def gitlogoutput = execute_working_dir('git', ['log', '-1', '--format=%at'],  "../.git")
        project.ext.revisionNumber = Integer.parseInt(gitlogoutput[0])
    } else {
        project.ext.revisionNumber = 1
    }
    System.setProperty("revision", "" + project.ext.revisionNumber);

    def version = System.getProperty("version")
    if(version == null || version.isEmpty()) {
        project.ext.versionNumber = 'SNAPSHOT'
    } else {
        project.ext.versionNumber = version
    }
    System.setProperty("version", project.ext.versionNumber);

    def versionPlusRevision = project.ext.versionNumber + '+' + project.ext.revisionNumber
    System.setProperty("version+revision", versionPlusRevision);
}

calculateBuildInfo()
