apply from: '../build/javalibrary.gradle'

dependencies {
    annotationProcessor libs.org.projectlombok.lombok
    
    implementation project(':lib-json'),
            project(':lib-messages-db'),
            libs.org.projectlombok.lombok
    testImplementation libs.org.junit.junit,
            libs.org.hamcrest.hamcrest.core,
            libs.org.hamcrest.hamcrest.library

}