apply from: '../build/javalibrary.gradle'

dependencies {
    implementation project(':lib-commonbase'),
            project(':lib-openbis-commonbase'),
            project(':lib-data-store-commonbase'),
            project(':lib-mail'),
            project(':lib-compress'),
            project(':lib-maintenance'),
            project(':lib-hierarchical-content'),
            project(':lib-archiver-db'),
            project(':lib-pathinfo-db'),
            project(':api-openbis-java'),
            libs.com.fasterxml.jackson.core.jackson.annotations,
            libs.com.fasterxml.jackson.core.jackson.databind,
            libs.lemnik.eodsql,
            libs.org.apache.commons.commons.compress,
            libs.de.schlichtherle.truezip
    testImplementation project(path: ':lib-hierarchical-content', configuration: 'tests'),
            project(path: ':lib-data-store-commonbase', configuration: 'tests'),
            project(path: ':lib-openbis-commonbase', configuration: 'tests'),
            libs.org.jmock.jmock
}
