apply from: '../build/javalibrary.gradle'

dependencies {
    implementation project(':lib-logging'),
            project(':lib-commonbase'),
            project(':lib-data-store-commonbase'),
            project(':lib-openbis-commonbase'),
            project(':lib-hierarchical-content'),
            project(':lib-maintenance'),
            libs.commons.io.commons.io
    testImplementation project(path: ':lib-data-store-commonbase', configuration: 'tests')
}
