apply from: '../build/javalibrary.gradle'

dependencies {
    implementation project(':lib-logging'),
            project(':lib-commonbase'),
            project(':lib-openbis-commonbase'),
            project(':lib-data-store-commonbase'),
            project(':lib-pathinfo-db'),
            project(':lib-hdf5'),
            project(':lib-compress'),
            project(':lib-transactional-file-system'),
            libs.sis.sis.base,
            libs.sis.sis.jhdf5,
            libs.org.apache.commons.commons.compress,
            libs.de.schlichtherle.truezip
    testImplementation project(path: ':lib-commonbase', configuration: 'tests'), libs.org.testng.testng, libs.org.junit.junit, libs.org.jmock.jmock,
            libs.org.apache.commons.commons.compress
}