apply from: '../build/javaproject.gradle'

dependencies {
    api project(':lib-logging'),
            project(':lib-commonbase'),
            project(':lib-db'),
            libs.sis.sis.base,
            //'apache:commons-dbcp:1.3-CISD',
            libs.org.apache.commons.commons.dbcp2,
            libs.org.apache.commons.commons.pool2,
            libs.com.h2database.h2,
            libs.org.postgresql.postgresql

    testImplementation project(path: ':lib-logging', configuration: 'tests'),
            project(path: ':lib-commonbase', configuration: 'tests'),
            libs.org.testng.testng,
            libs.org.junit.junit,
            libs.org.jmock.jmock,
            libs.fjelmer.classycle
} 
