apply from: '../build/javaproject.gradle'

dependencies {
    api project(':lib-logging'),
            libs.commons.io.commons.io,
            libs.org.apache.commons.commons.lang3,
            libs.sis.sis.base,
            libs.rinn.restrictions

    testImplementation project(path: ':lib-logging', configuration: 'tests'),
            libs.org.testng.testng,
            libs.org.junit.junit,
            libs.org.hamcrest.hamcrest.integration,
            libs.org.hamcrest.hamcrest.library,
            libs.fjelmer.classycle

    testImplementation(libs.org.jmock.jmock) {
        exclude group: 'hamcrest', module: 'hamcrest-core'
        exclude group: 'hamcrest', module: 'hamcrest-library'
    }
}

jar {
    duplicatesStrategy 'include'
    from('targets/dist') {
        include 'BUILD*INFO'
    }
    from sourceSets.main.output + sourceSets.test.output
}
