label = ${eln-lims.as.services.imports-api.label:Imports API}
class = ch.ethz.sis.openbis.generic.server.asapi.v3.helper.service.JythonBasedCustomASServiceExecutor
script-path = ${eln-lims.as.services.imports-api.script-path:importFacade.py}

# RO-Crate export config
ro-crate.url=${eln-lims.as.services.imports-api.ro-crate.url:http://localhost:8086/openbis/open-api/ro-crate}