apply plugin: 'java-library'
apply plugin: 'application'

apply from: '../build/repository.gradle'
repositories repositoryConfig

dependencies {
    api project(':lib-microservice-server'), project(':lib-logging')
    api libs.openbis.openbis.v3.api.batteries.included
}

mainClassName = "ch.ethz.sis.microservices.download.server.startup.Main"

distZip {
    eachFile { file ->
        if (file.name.endsWith('-sources.jar') || file.name.endsWith('-javadoc.jar')) {
            file.exclude()
        }
    }
    into(project.name) {
        from './conf'
        include '*'
    }
    into(project.name) {
        from './'
        include 'README.md'
    }
}
