evaluationDependsOn(':lib-commonbase')
evaluationDependsOn(':lib-common')
evaluationDependsOn(':lib-dbmigration')
evaluationDependsOn(':lib-authentication')

apply from: '../build/javaproject.gradle'

dependencies {
    api project(':lib-common'),
            project(':lib-dbmigration'),
            project(':lib-authentication'),
            project(':lib-hierarchical-content'),
            project(':lib-hdf5'),
            libs.googlecode.jsonrpc4j,
            libs.com.fasterxml.jackson.core.jackson.databind,
            libs.com.fasterxml.jackson.core.jackson.annotations,
            libs.org.reflections.reflections,
            libs.lemnik.eodsql,
            libs.org.springframework.spring.jdbc,
            libs.org.springframework.spring.tx,
            libs.org.apache.commons.commons.collections4,
            libs.de.schlichtherle.truezip





    testImplementation project(path: ':lib-commonbase', configuration: 'tests'),
            project(path: ':lib-common', configuration: 'tests'),
            project(path: ':lib-dbmigration', configuration: 'tests'),
            project(path: ':lib-authentication', configuration: 'tests'),
            libs.fjelmer.classycle,
            libs.org.testng.testng,
            libs.org.junit.junit,
            libs.org.jmock.jmock,
            libs.org.eclipse.jetty.ee10.jetty.ee10.servlet,
            libs.org.hamcrest.hamcrest.integration,
            libs.org.hamcrest.hamcrest.library,
            libs.org.slf4j.slf4j.api,
            libs.org.slf4j.slf4j.jdk14,
            libs.org.eclipse.jetty.jetty.server
}
