
CREATE OR REPLACE RULE data_insert AS
  ON INSERT TO data DO INSTEAD
     INSERT INTO data_all (
       id,
       frozen,
       frozen_for_children,
       frozen_for_parents,
       frozen_for_comps,
       frozen_for_conts,
       code,
       del_id,
       orig_del,
       expe_id,
       expe_frozen,
       dast_id,
       data_producer_code,
       dsty_id,
       is_derived,
       is_valid,
       modification_timestamp,
       access_timestamp,
       pers_id_registerer,
       pers_id_modifier,
       production_timestamp,
       registration_timestamp,
       samp_id,
       samp_frozen,
       version,
       data_set_kind,
       meta_data,
       afs_data
     ) VALUES (
       NEW.id,
       NEW.frozen,
       NEW.frozen_for_children,
       NEW.frozen_for_parents,
       NEW.frozen_for_comps,
       NEW.frozen_for_conts,
       NEW.code,
       NEW.del_id,
       NEW.orig_del,
       NEW.expe_id,
       NEW.expe_frozen,
       NEW.dast_id,
       NEW.data_producer_code,
       NEW.dsty_id,
       NEW.is_derived,
       NEW.is_valid,
       NEW.modification_timestamp,
       NEW.access_timestamp,
       NEW.pers_id_registerer,
       NEW.pers_id_modifier,
       NEW.production_timestamp,
       NEW.registration_timestamp,
       NEW.samp_id,
       NEW.samp_frozen,
       NEW.version,
       NEW.data_set_kind,
       NEW.meta_data,
       NEW.afs_data
     )
     RETURNING
       id,
       code,
       dsty_id,
       dast_id,
       expe_id,
       expe_frozen,
       data_producer_code,
       production_timestamp,
       samp_id,
       samp_frozen,
       registration_timestamp,
       access_timestamp,
       pers_id_registerer,
       pers_id_modifier,
       is_valid,
       modification_timestamp,
       is_derived,
       del_id,
       orig_del,
       version,
       data_set_kind,
       frozen,
       frozen_for_children,
       frozen_for_parents,
       frozen_for_comps,
       frozen_for_conts,
       tsvector_document,
       meta_data,
       afs_data;

DROP RULE IF EXISTS data_set_relationships_insert ON data_set_relationships;

CREATE OR REPLACE RULE data_set_relationships_insert AS
    ON INSERT TO data_set_relationships DO INSTEAD
       INSERT INTO data_set_relationships_all (
         data_id_parent,
         parent_frozen,
         cont_frozen,
         data_id_child,
         child_frozen,
         comp_frozen,
         pers_id_author,
         relationship_id,
         ordinal,
         registration_timestamp,
         modification_timestamp
       ) VALUES (
         NEW.data_id_parent,
         NEW.parent_frozen,
         NEW.cont_frozen,
         NEW.data_id_child,
         NEW.child_frozen,
         NEW.comp_frozen,
         NEW.pers_id_author,
         NEW.relationship_id,
         NEW.ordinal,
         NEW.registration_timestamp,
         NEW.modification_timestamp
       )
       RETURNING
         data_id_parent,
         parent_frozen,
         cont_frozen,
         data_id_child,
         child_frozen,
         comp_frozen,
         relationship_id,
         ordinal,
         del_id,
         pers_id_author,
      registration_timestamp,
      modification_timestamp;

DROP RULE IF EXISTS experiment_insert ON experiments;

CREATE OR REPLACE RULE experiment_insert AS
  ON INSERT TO experiments DO INSTEAD
     INSERT INTO experiments_all (
       id,
       frozen,
       frozen_for_samp,
       frozen_for_data,
       code,
       del_id,
       orig_del,
       exty_id,
       is_public,
       modification_timestamp,
       perm_id,
       pers_id_registerer,
       pers_id_modifier,
       proj_id,
       proj_frozen,
       registration_timestamp,
       version,
       meta_data,
       immutable_data_timestamp
     ) VALUES (
       NEW.id,
       NEW.frozen,
       NEW.frozen_for_samp,
       NEW.frozen_for_data,
       NEW.code,
       NEW.del_id,
       NEW.orig_del,
       NEW.exty_id,
       NEW.is_public,
       NEW.modification_timestamp,
       NEW.perm_id,
       NEW.pers_id_registerer,
       NEW.pers_id_modifier,
       NEW.proj_id,
       NEW.proj_frozen,
       NEW.registration_timestamp,
       NEW.version,
       NEW.meta_data,
       NEW.immutable_data_timestamp
     )
     RETURNING
       id,
       perm_id,
       code,
       exty_id,
       pers_id_registerer,
       pers_id_modifier,
       registration_timestamp,
       modification_timestamp,
       proj_id,
       proj_frozen,
       del_id,
       orig_del,
       is_public,
       version,
       frozen,
       frozen_for_samp,
       frozen_for_data,
       tsvector_document,
       meta_data,
       immutable_data_timestamp;

DROP RULE IF EXISTS sample_insert ON samples;

CREATE OR REPLACE RULE sample_insert AS
  ON INSERT TO samples DO INSTEAD
     INSERT INTO samples_all (
       id,
       frozen,
       frozen_for_comp,
       frozen_for_children,
       frozen_for_parents,
       frozen_for_data,
       code,
       del_id,
       orig_del,
       expe_id,
       expe_frozen,
       proj_id,
       proj_frozen,
       modification_timestamp,
       perm_id,
       pers_id_registerer,
       pers_id_modifier,
       registration_timestamp,
       samp_id_part_of,
       cont_frozen,
       saty_id,
       space_id,
       space_frozen,
       version,
       meta_data,
       immutable_data_timestamp
     ) VALUES (
       NEW.id,
       NEW.frozen,
       NEW.frozen_for_comp,
       NEW.frozen_for_children,
       NEW.frozen_for_parents,
       NEW.frozen_for_data,
       NEW.code,
       NEW.del_id,
       NEW.orig_del,
       NEW.expe_id,
       NEW.expe_frozen,
       NEW.proj_id,
       NEW.proj_frozen,
       NEW.modification_timestamp,
       NEW.perm_id,
       NEW.pers_id_registerer,
       NEW.pers_id_modifier,
       NEW.registration_timestamp,
       NEW.samp_id_part_of,
       NEW.cont_frozen,
       NEW.saty_id,
       NEW.space_id,
       NEW.space_frozen,
       NEW.version,
       NEW.meta_data,
       NEW.immutable_data_timestamp
     )
     RETURNING
       id,
       perm_id,
       code,
       proj_id,
       proj_frozen,
       expe_id,
       expe_frozen,
       saty_id,
       registration_timestamp,
       modification_timestamp,
       pers_id_registerer,
       pers_id_modifier,
       del_id,
       orig_del,
       space_id,
       space_frozen,
       samp_id_part_of,
       cont_frozen,
       version,
       frozen,
       frozen_for_comp,
       frozen_for_children,
       frozen_for_parents,
       frozen_for_data,
       tsvector_document,
       sample_identifier,
       meta_data,
       immutable_data_timestamp;

DROP RULE IF EXISTS sample_relationships_insert ON sample_relationships;

CREATE OR REPLACE RULE sample_relationships_insert AS
    ON INSERT TO sample_relationships DO INSTEAD
       INSERT INTO sample_relationships_all (
         id,
         sample_id_parent,
         parent_frozen,
         relationship_id,
         sample_id_child,
         child_frozen,
         pers_id_author,
         registration_timestamp,
         modification_timestamp,
         child_annotations,
         parent_annotations
       ) VALUES (
         NEW.id,
         NEW.sample_id_parent,
         NEW.parent_frozen,
         NEW.relationship_id,
         NEW.sample_id_child,
         NEW.child_frozen,
         NEW.pers_id_author,
         NEW.registration_timestamp,
         NEW.modification_timestamp,
         NEW.child_annotations,
         NEW.parent_annotations
       )
       RETURNING
         id,
         sample_id_parent,
         parent_frozen,
         relationship_id,
         sample_id_child,
         child_frozen,
         del_id,
         pers_id_author,
         registration_timestamp,
         modification_timestamp,
         child_annotations,
         parent_annotations;

CREATE OR REPLACE RULE data_update AS
    ON UPDATE TO data DO INSTEAD
UPDATE data_all
SET code = NEW.code,
    frozen = NEW.frozen,
    frozen_for_children = NEW.frozen_for_children,
    frozen_for_parents = NEW.frozen_for_parents,
    frozen_for_comps = NEW.frozen_for_comps,
    frozen_for_conts = NEW.frozen_for_conts,
    del_id = NEW.del_id,
    orig_del = NEW.orig_del,
    expe_id = NEW.expe_id,
    expe_frozen = NEW.expe_frozen,
    dast_id = NEW.dast_id,
    data_producer_code = NEW.data_producer_code,
    dsty_id = NEW.dsty_id,
    is_derived = NEW.is_derived,
    is_valid = NEW.is_valid,
    modification_timestamp = NEW.modification_timestamp,
    access_timestamp = NEW.access_timestamp,
    pers_id_registerer = NEW.pers_id_registerer,
    pers_id_modifier = NEW.pers_id_modifier,
    production_timestamp = NEW.production_timestamp,
    registration_timestamp = NEW.registration_timestamp,
    samp_id = NEW.samp_id,
    samp_frozen = NEW.samp_frozen,
    version = NEW.version,
    data_set_kind = NEW.data_set_kind,
    meta_data = NEW.meta_data,
    afs_data = NEW.afs_data
WHERE id = NEW.id
    RETURNING
         id,
         code,
         dsty_id,
         dast_id,
         expe_id,
         expe_frozen,
         data_producer_code,
         production_timestamp,
         samp_id,
         samp_frozen,
         registration_timestamp,
         access_timestamp,
         pers_id_registerer,
         pers_id_modifier,
         is_valid,
         modification_timestamp,
         is_derived,
         del_id,
         orig_del,
         version,
         data_set_kind,
         frozen,
         frozen_for_children,
         frozen_for_parents,
         frozen_for_comps,
         frozen_for_conts,
         tsvector_document,
         meta_data,
         afs_data;
