-- Migration from 204 to 205

CREATE TABLE TYPE_GROUPS (
    ID TECH_ID NOT NULL,
    CODE CODE NOT NULL,
    PERS_ID_REGISTERER TECH_ID NOT NULL,
    REGISTRATION_TIMESTAMP TIME_STAMP_DFL NOT NULL,
    PERS_ID_MODIFIER TECH_ID,
    MODIFICATION_TIMESTAMP TIME_STAMP DEFAULT CURRENT_TIMESTAMP,
    IS_MANAGED_INTERNALLY BOOLEAN_CHAR NOT NULL DEFAULT 'F',
    META_DATA JSONB
);

ALTER TABLE TYPE_GROUPS ADD CONSTRAINT TYPE_GROUPS_CODE_UK UNIQUE(CODE);
ALTER TABLE TYPE_GROUPS ADD CONSTRAINT TYPE_GROUPS_PK PRIMARY KEY(ID);
ALTER TABLE TYPE_GROUPS ADD CONSTRAINT TG_PERS_FK FOREIGN KEY (PERS_ID_REGISTERER) REFERENCES PERSONS(ID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE TYPE_GROUPS ADD CONSTRAINT TG_PERS_FK_MOD FOREIGN KEY (PERS_ID_MODIFIER) REFERENCES PERSONS(ID) DEFERRABLE INITIALLY DEFERRED;

CREATE SEQUENCE TYPE_GROUPS_ID_SEQ;

CREATE TABLE SAMPLE_TYPE_TYPE_GROUPS (
    SATY_ID TECH_ID NOT NULL,
    TG_ID TECH_ID NOT NULL,
    PERS_ID_REGISTERER TECH_ID NOT NULL,
    REGISTRATION_TIMESTAMP TIME_STAMP_DFL NOT NULL,
    IS_MANAGED_INTERNALLY BOOLEAN_CHAR NOT NULL DEFAULT 'F'
);

ALTER TABLE SAMPLE_TYPE_TYPE_GROUPS ADD CONSTRAINT SAMPLE_TYPE_TYPE_GROUPS_UK UNIQUE (SATY_ID, TG_ID);


ALTER TABLE SAMPLE_TYPE_TYPE_GROUPS ADD CONSTRAINT STTG_SATY_FK FOREIGN KEY (SATY_ID) REFERENCES SAMPLE_TYPES(ID) ON DELETE CASCADE;
ALTER TABLE SAMPLE_TYPE_TYPE_GROUPS ADD CONSTRAINT STTG_TG_FK FOREIGN KEY (TG_ID) REFERENCES TYPE_GROUPS(ID) ON DELETE CASCADE;
ALTER TABLE SAMPLE_TYPE_TYPE_GROUPS ADD CONSTRAINT STTG_PERS_FK FOREIGN KEY (PERS_ID_REGISTERER) REFERENCES PERSONS(ID) DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX STTG_SATY_FK_I ON SAMPLE_TYPE_TYPE_GROUPS (SATY_ID);
CREATE INDEX STTG_TG_FK_I ON SAMPLE_TYPE_TYPE_GROUPS (TG_ID);
CREATE INDEX STTG_PERS_FK_I ON SAMPLE_TYPE_TYPE_GROUPS (PERS_ID_REGISTERER);


