#
#  Copyright ETH 2025 Zürich, Scientific IT Services
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#
# prefix needed for setting service.properties from system properties or environment variables
system.property.prefix=ro-crate.
# Server Properties
httpServerPort=8086
httpServerTimeout=120s
sessionWorkSpace=../test-integration/targets/ro-crate/server-ro-crate/session-workspace/

enablePreview=png,jpeg,jpg,gif,bmp,tiff
enablePreviewSizeInBytes=100000000

# AFS Client Properties
httpMaxContentLength=1540165
maxReadSizeInBytes=1048576

# openBIS Client Properties
openBISUrl=http://localhost:9858
openBISTimeout=300000
# Quarkus logging
quarkus.log.file.enable=true
quarkus.log.file.path=logs/app.log
quarkus.log.level=DEBUG

# mail client Properties
mailFrom=rocrate_server@localhost
mailSmtpHost=file://../test-integration/targets/ro-crate-email
mailSmtpUser=
mailSmtpPassword=
