package ch.eth.sis.rocrate.parser.helper;

import ch.ethz.sis.openbis.generic.asapi.v3.dto.common.interfaces.IEntityType;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.entitytype.EntityKind;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.entitytype.id.EntityTypePermId;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.sample.SampleType;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.sample.fetchoptions.SampleTypeFetchOptions;
import ch.ethz.sis.openbis.generic.server.xls.importer.ImportOptions;
import ch.ethz.sis.openbis.generic.server.xls.importer.enums.ImportModes;
import ch.ethz.sis.openbis.generic.server.xls.importer.enums.ImportTypes;
import ch.ethz.sis.openbis.generic.server.xls.importer.helper.BasicImportHelper;
import ch.ethz.sis.openbis.generic.server.xls.importer.helper.SampleTypeImportHelper;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class ObjectTypeHelper extends BasicImportHelper
{
    Map<String, SampleType> accumulator = new HashMap<>();

    public ObjectTypeHelper(ImportModes mode,
            ImportOptions options)
    {
        super(mode, options);
    }

    @Override
    protected ImportTypes getTypeName()
    {
        return null;
    }

    @Override
    protected boolean isObjectExist(Map<String, Integer> header, List<String> values)
    {
        return false;
    }

    @Override
    protected void createObject(Map<String, Integer> header, List<String> values, int page,
            int line)
    {
        String code = getValueByColumnName(header, values, SampleTypeImportHelper.Attribute.Code);
        String description =
                getValueByColumnName(header, values, SampleTypeImportHelper.Attribute.Description);
        String autoGenerateCodes = getValueByColumnName(header, values,
                SampleTypeImportHelper.Attribute.AutoGenerateCodes);
        String generatedCodePrefix = getValueByColumnName(header, values,
                SampleTypeImportHelper.Attribute.GeneratedCodePrefix);

        SampleType sampleType = new SampleType();

        SampleTypeFetchOptions fetchOptions = new SampleTypeFetchOptions();
        fetchOptions.withPropertyAssignments();
        sampleType.setFetchOptions(fetchOptions);
        sampleType.setPropertyAssignments(new ArrayList<>());

        sampleType.setCode(code);
        sampleType.setDescription(description);
        sampleType.setAutoGeneratedCode(Boolean.parseBoolean(autoGenerateCodes));
        if (generatedCodePrefix != null && !generatedCodePrefix.isEmpty())
        {
            sampleType.setGeneratedCodePrefix(generatedCodePrefix);
        }
        sampleType.setManagedInternally(false);

        accumulator.put(code, sampleType);

    }

    @Override
    protected void updateObject(Map<String, Integer> header, List<String> values, int page,
            int line)
    {

    }

    @Override
    protected void validateHeader(Map<String, Integer> header)
    {

    }

    public Map<EntityTypePermId, IEntityType> getResult()
    {
        return accumulator.values().stream()
                .collect(Collectors.toMap(x -> new EntityTypePermId(x.getCode(), EntityKind.SAMPLE),
                        x -> x));
    }

    SampleType getObjectType(String key)
    {
        return accumulator.get(key);
    }

}
