plugins {
    id 'java'
    id 'application'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile) {
    options.compilerArgs << '-parameters'
}

apply from: '../build/repository.gradle'
repositories repositoryConfig

dependencies {
                // Ro-crate library
    implementation libs.edu.kit.datamanager.ro.crate.java,
                    libs.com.fasterxml.jackson.core.jackson.core,
                    libs.com.fasterxml.jackson.core.jackson.databind,
                    // Command Line App
                    libs.org.apache.commons.commons.collections4,
                    libs.commons.cli.commons.cli.v14,
                    // Our libraries
                    project(':api-openbis-java'),
                    project(':lib-ro-crate'),
                    project(':lib-rdf')

    testImplementation libs.org.junit.junit, libs.org.hamcrest.hamcrest.core, libs.org.hamcrest.hamcrest.library, libs.org.jmock.jmock
}


test {
    useJUnit();
    systemProperty "java.awt.headless", "true";
    jvmArgs "-Djava.awt.headless=true"
}
