apply from: '../build/javalibrary.gradle'

dependencies {
    api project(':lib-logging'),
            project(':lib-db')
    testImplementation project(path: ':lib-commonbase', configuration: 'tests'),
            libs.org.testng.testng,
            libs.org.junit.junit,
            libs.org.jmock.jmock
}