apply from: '../build/javalibrary.gradle'

dependencies {
    api project(':lib-commonbase'),
            libs.sis.sis.base,
            libs.lemnik.eodsql,
            libs.it.unimi.dsi.fastutil
    testImplementation libs.org.testng.testng,
            libs.org.junit.junit,
            libs.org.jmock.jmock
}