package parser.helper;

import ch.ethz.sis.openbis.generic.asapi.v3.dto.common.interfaces.IEntityType;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.entitytype.EntityKind;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.entitytype.id.EntityTypePermId;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.sample.SampleType;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.sample.fetchoptions.SampleTypeFetchOptions;
import parser.IAttribute;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class ObjectTypeHelper extends BasicImportHelper
{

    public enum Attribute implements IAttribute
    {
        Version("Version", false, false),
        Code("Code", true, true),
        Description("Description", true, false),
        AutoGenerateCodes("Auto generate codes", true, false),
        ValidationScript("Validation script", true, false),
        GeneratedCodePrefix("Generated code prefix", true, false),
        OntologyId("Ontology Id", false, false),
        OntologyVersion("Ontology Version", false, false),
        OntologyAnnotationId("Ontology Annotation Id", false, false),
        Internal("Internal", false, false);

        private final String headerName;

        private final boolean mandatory;

        private final boolean upperCase;

        Attribute(String headerName, boolean mandatory, boolean upperCase)
        {
            this.headerName = headerName;
            this.mandatory = mandatory;
            this.upperCase = upperCase;
        }

        public String getHeaderName()
        {
            return headerName;
        }

        @Override
        public boolean isMandatory()
        {
            return mandatory;
        }

        @Override
        public boolean isUpperCase()
        {
            return upperCase;
        }
    }

    Map<String, SampleType> accumulator = new HashMap<>();

    public ObjectTypeHelper()
    {
    }

    @Override
    protected boolean isObjectExist(Map<String, Integer> header, List<String> values)
    {
        return false;
    }

    @Override
    protected void createObject(Map<String, Integer> header, List<String> values, int page,
            int line)
    {
        String code = getValueByColumnName(header, values, Attribute.Code);
        String description =
                getValueByColumnName(header, values, Attribute.Description);
        String autoGenerateCodes = getValueByColumnName(header, values,
                Attribute.AutoGenerateCodes);
        String generatedCodePrefix = getValueByColumnName(header, values,
                Attribute.GeneratedCodePrefix);

        SampleType sampleType = new SampleType();

        SampleTypeFetchOptions fetchOptions = new SampleTypeFetchOptions();
        fetchOptions.withPropertyAssignments();
        sampleType.setFetchOptions(fetchOptions);
        sampleType.setPropertyAssignments(new ArrayList<>());

        sampleType.setCode(code);
        sampleType.setDescription(description);
        sampleType.setAutoGeneratedCode(Boolean.parseBoolean(autoGenerateCodes));
        if (generatedCodePrefix != null && !generatedCodePrefix.isEmpty())
        {
            sampleType.setGeneratedCodePrefix(generatedCodePrefix);
        }
        sampleType.setManagedInternally(false);

        accumulator.put(code, sampleType);

    }

    @Override
    protected void updateObject(Map<String, Integer> header, List<String> values, int page,
            int line)
    {

    }

    @Override
    protected void validateHeader(Map<String, Integer> header)
    {

    }

    public Map<EntityTypePermId, IEntityType> getResult()
    {
        return accumulator.values().stream()
                .collect(Collectors.toMap(x -> new EntityTypePermId(x.getCode(), EntityKind.SAMPLE),
                        x -> x));
    }

    SampleType getObjectType(String key)
    {
        return accumulator.get(key);
    }

}
