ALTER TABLE LAST_FEEDING_EVENT RENAME COLUMN REGISTRATION_TIMESTAMP TO LAST_SEEN_TIMESTAMP;
ALTER TABLE LAST_FEEDING_EVENT ADD COLUMN DATA_STORE_KIND CODE;

UPDATE LAST_FEEDING_EVENT SET DATA_STORE_KIND = 'DSS';

ALTER TABLE LAST_FEEDING_EVENT ALTER COLUMN DATA_STORE_KIND SET NOT NULL;