apply from: '../build/javalibrary.gradle'

dependencies {
    implementation project(':lib-openbis-commonbase'),
            project(':api-openbis-java'),
            libs.net.sourceforge.javacsv.javacsv
    testImplementation project(path: ':lib-openbis-commonbase', configuration: 'tests'),
            libs.org.jmock.jmock
}