# Module: http
--module=http
### HTTP Connector Configuration
## HTTP port to listen on
jetty.http.port=9002
## HTTP idle timeout in milliseconds
jetty.http.idleTimeout=30000
## HTTP Socket.soLingerTime in seconds. (-1 to disable)
# http.soLingerTime=-1
## Parameters to control the number and priority of acceptors and selectors
# jetty.http.selectors=-1
# jetty.http.acceptors=1
# jetty.http.selectorPriorityDelta=0
# jetty.http.acceptorPriorityDelta=0
