apply plugin: 'java'
apply plugin: 'application'

compileJava {
    options.compilerArgs << '-parameters'
}

sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21

apply from: '../build/repository.gradle'
repositories repositoryConfig

dependencies {
    annotationProcessor libs.org.projectlombok.lombok
    implementation  project(':lib-json'),
                    project(':lib-logging'),
                    libs.org.projectlombok.lombok,
                    libs.com.fasterxml.jackson.core.jackson.annotations,
                    libs.com.fasterxml.jackson.core.jackson.core,
                    libs.com.fasterxml.jackson.core.jackson.databind,
                    libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310;
    testImplementation libs.org.junit.junit
    testRuntimeOnly libs.org.hamcrest.hamcrest.core
}

mainClassName = "ch.ethz.sis.afs.startup.Main"