evaluationDependsOn(':lib-commonbase')
evaluationDependsOn(':lib-common')

apply from: '../build/javaproject.gradle'

dependencies {
    api project(':lib-common')
            //'eclipse:jetty-http:12.1.1'

    testImplementation project(path: ':lib-commonbase', configuration: 'tests'),
            project(path: ':lib-common', configuration: 'tests'),
            'testng:testng:6.8-CISD',
            'junit:junit:4.13.2',
            'jmock:jmock:2.5.1',
            'fjelmer:classycle:1.4.2'

} 
