evaluationDependsOn(':lib-commonbase')
evaluationDependsOn(':lib-common')

apply from: '../build/javaproject.gradle'

dependencies {
    api project(':lib-common')
            //'eclipse:jetty-http:12.1.1'

    testImplementation project(path: ':lib-commonbase', configuration: 'tests'),
            project(path: ':lib-common', configuration: 'tests'),
            libs.org.testng.testng,
            libs.org.junit.junit,
            libs.org.jmock.jmock,
            libs.fjelmer.classycle

} 
