plugins {
    id 'java'
    id 'application'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile) {
    options.compilerArgs << '-parameters'
}

apply from: '../build/repository.gradle'
repositories repositoryConfig

apply from: '../build/common-resolutions.gradle'

dependencies {
    implementation libs.bundles.org.apache.jena.jena,
            libs.org.apache.poi.poi,
            libs.org.apache.poi.poi.ooxml,
            libs.org.apache.poi.poi.ooxml.lite,
            libs.commons.cli.commons.cli.v14
    implementation libs.org.xerial.sqlite.jdbc
    implementation project(':api-openbis-java')

    testImplementation libs.org.junit.junit, libs.org.hamcrest.hamcrest.core, libs.org.hamcrest.hamcrest.library
}

tasks.register('buildRdfTool', Jar) {
    zip64 = true
    dependsOn tasks.build
    duplicatesStrategy 'include'

    archiveBaseName.set('lib-rdf-tool')
    includeEmptyDirs = false

    manifest {
        attributes(
                'Main-Class': 'ch.ethz.sis.rdf.main.RDFCommandLine'
        )
    }

    from(zipTree(tasks.jar.outputs.files.singleFile)) {
        include '**/*'
    }

    from(
            configurations.runtimeClasspath
                    .filter { it.name.toLowerCase().endsWith('.jar') }
                    .collect { zipTree(it) }
    ) {
        include '**/*'
        exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
    }
}


tasks.register('buildRdfImport', Jar) {
    zip64 = true
    dependsOn tasks.build
    duplicatesStrategy 'include'

    archiveBaseName.set('lib-rdf-import')
    includeEmptyDirs = false

    manifest {
        attributes(
                'Main-Class': 'ch.ethz.sis.tools.BasicImport'
        )
    }

    from(zipTree(tasks.jar.outputs.files.singleFile)) {
        include '**/*'
    }

    from(
            configurations.runtimeClasspath
                    .filter { it.name.toLowerCase().endsWith('.jar') }
                    .collect { zipTree(it) }
    ) {
        include '**/*'
        exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
    }
}

tasks.register('buildRepairTool', Jar) {
    zip64 = true
    dependsOn tasks.build
    duplicatesStrategy 'include'

    archiveBaseName.set('lib-rdf-repair')
    includeEmptyDirs = false

    manifest {
        attributes(
                'Main-Class': 'ch.ethz.sis.tools.referencecheck.ReferenceCheck'
        )
    }

    from(zipTree(tasks.jar.outputs.files.singleFile)) {
        include '**/*'
    }

    from(
            configurations.runtimeClasspath
                    .filter { it.name.toLowerCase().endsWith('.jar') }
                    .collect { zipTree(it) }
    ) {
        include '**/*'
        exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
    }
}


tasks.register('buildCountTool', Jar) {
    zip64 = true
    dependsOn tasks.build
    duplicatesStrategy 'include'

    archiveBaseName.set('lib-rdf-count')
    includeEmptyDirs = false

    manifest {
        attributes(
                'Main-Class': 'ch.ethz.sis.tools.ResourceCount'
        )
    }

    from(zipTree(tasks.jar.outputs.files.singleFile)) {
        include '**/*'
    }

    from(
            configurations.runtimeClasspath
                    .filter { it.name.toLowerCase().endsWith('.jar') }
                    .collect { zipTree(it) }
    ) {
        include '**/*'
        exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
    }
}


tasks.register('buildUpdateTool', Jar) {
    zip64 = true
    dependsOn tasks.build
    duplicatesStrategy 'include'

    archiveBaseName.set('lib-rdf-update')
    includeEmptyDirs = false

    manifest {
        attributes(
                'Main-Class': 'ch.ethz.sis.tools.vocabfix.PropertyUpdate'
        )
    }

    from(zipTree(tasks.jar.outputs.files.singleFile)) {
        include '**/*'
    }

    from(configurations.runtimeClasspath.collect { zipTree(it) }) {
        include '**/*'
        exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
    }
}
