apply from: '../build/javalibrary.gradle'

dependencies {
    api project(':lib-logging'),
            project(':lib-commonbase'),
            libs.com.fasterxml.jackson.core.jackson.databind
    testImplementation libs.org.testng.testng,
            libs.org.junit.junit,
            libs.org.jmock.jmock,
            libs.org.hamcrest.hamcrest.integration,
            libs.org.hamcrest.hamcrest.library
}
