evaluationDependsOn(':lib-commonbase')

apply from: '../build/javaproject.gradle'

dependencies {
    api project(':lib-commonbase'),
        libs.org.springframework.spring.webmvc,
        libs.org.springframework.spring.web,
        libs.org.springframework.spring.core,
        libs.org.springframework.spring.aop,
        libs.org.springframework.spring.context,
        libs.org.springframework.spring.beans,
        libs.jakarta.servlet.jakarta.servlet.api.v60,

        libs.cisd.cisd.args4j,
        libs.python.jython,
        libs.python.jython27,
        libs.org.apache.commons.commons.text,
        //'javax.annotation:javax.annotation-api:1.3.2',
        libs.jakarta.annotation.jakarta.annotation.api,
        libs.javax.activation.activation,
        //'javax.xml.bind:jaxb-api:2.3.1',
        libs.jakarta.xml.bind.jakarta.xml.bind.api,
        libs.org.glassfish.jaxb.txw2,
        libs.org.glassfish.jaxb.jaxb.core,
        libs.org.glassfish.jaxb.jaxb.runtime,
        libs.org.glassfish.main.javaee.api.javax.jws,
        libs.com.sun.istack.istack.commons.runtime,
        libs.org.apache.poi.poi,
        libs.com.twmacinta.fast.md5,
        libs.org.testng.testng, // this should ideally go away
        libs.org.junit.junit, // this should go away
        libs.marathon.marathon.spring.util,
        libs.lemnik.eodsql,
        libs.it.unimi.dsi.fastutil,
        libs.sis.sis.base,
        libs.rinn.restrictions,
        libs.org.apache.httpcomponents.httpclient.v436,
        libs.org.eclipse.jetty.jetty.client

    api(libs.org.eclipse.jetty.compression.jetty.compression.common) {
        exclude group: "org.eclipse.jetty", module: "jetty-http"
    }
    api libs.org.apache.commons.commons.csv,
        libs.com.fasterxml.jackson.core.jackson.databind,
        libs.org.slf4j.slf4j.api,
        libs.deltavisio.http.invoker.reloaded,

        libs.googlecode.jsonrpc4j,
        libs.com.fasterxml.jackson.core.jackson.databind,
        libs.org.reflections.reflections

    testImplementation project(path: ':lib-logging', configuration: 'tests'),
            project(path: ':lib-commonbase', configuration: 'tests'),
            libs.org.testng.testng,
            libs.org.junit.junit,
            libs.org.hamcrest.hamcrest.integration,
            libs.org.hamcrest.hamcrest.library,
            libs.fjelmer.classycle,
           libs.org.eclipse.jetty.ee10.jetty.ee10.servlet
            //'org.glassfish.jaxb:jaxb-runtime:4.0.5'

    testImplementation(libs.org.jmock.jmock) {
        exclude group: 'hamcrest', module: 'hamcrest-core'
        exclude group: 'hamcrest', module: 'hamcrest-library'
    }
}

test {
    if (System.getProperty("openbis.proxyHost") != null) {
        systemProperty "openbis.proxyHost", System.getProperty("openbis.proxyHost")
    }
    if (System.getProperty("openbis.proxyPort") != null) {
        systemProperty "openbis.proxyPort", System.getProperty("openbis.proxyPort")
    }

    // remove DISPLAY completely
    environment.remove("DISPLAY")
}

testJar {
    from "source/java/genericCommonContext.xml"
}

sourceSets {
    main {
        resources {
            srcDirs = ['source/java']
        }
    }
}
