apply from: '../build/javalibrary.gradle'

dependencies {
    implementation project(':lib-logging'),
            project(':lib-commonbase'),
            'org.springframework:spring-context:6.2.15',
            'org.springframework:spring-core:6.2.15'
    testImplementation project(path: ':lib-commonbase', configuration: 'tests'),
            'testng:testng:6.8-CISD'
}