apply from: '../build/javalibrary.gradle'

dependencies {
    implementation project(':lib-logging'),
            project(':lib-commonbase'),
            libs.org.springframework.spring.context,
            libs.org.springframework.spring.core
    testImplementation project(path: ':lib-commonbase', configuration: 'tests'),
            libs.org.testng.testng
}
