label = ${eln-lims.as.services.zenodo-exports-api.label:Zenodo Exports API}
class = ch.ethz.sis.openbis.generic.server.asapi.v3.helper.service.JythonBasedCustomASServiceExecutor
script-path = ${eln-lims.as.services.zenodo-exports-api.script-path:zenodoExports.py}
zenodoUrl=${zenodo-exports-api-zenodoUrl:https://zenodo.org}
httpProxyURL=${zenodo-exports-api-http-proxy-url:}
httpProxyPort=${zenodo-exports-api-http-proxy-port:}
share-id = ${eln-lims.as.services.zenodo-exports-api.share-id:}