buildscript {
    apply from: '../build/repository.gradle'

    repositories repositoryConfig

    repositories {
        ivy {
            ivyPattern "https://sissource.ethz.ch/openbis/openbis-public/openbis-ivy/-/raw/main/owasp/dependency-check-gradle/12.2.0/[organisation]/[module]/ivy-[revision].xml"
            artifactPattern "https://sissource.ethz.ch/openbis/openbis-public/openbis-ivy/-/raw/main/owasp/dependency-check-gradle/12.2.0/[organisation]/[module]/jars/[artifact]-[revision](-[classifier]).[ext]"
            artifactPattern "https://sissource.ethz.ch/openbis/openbis-public/openbis-ivy/-/raw/main/owasp/dependency-check-gradle/12.2.0/[organisation]/[module]/bundles/[artifact]-[revision](-[classifier]).[ext]"
        }
    }

    repositories {
        //gradlePluginPortal()
        //mavenCentral()
    }
    dependencies {
        classpath("org.owasp:dependency-check-gradle:12.2.0")
    }
}

// MORE RECENT WAY OF APPLYING GRADLE PLUGINS: but it works only if gradlePluginPortal() is reachable
//plugins {
    //id("org.owasp.dependencycheck") version "12.2.0"
//}

apply from: '../build/javaproject.gradle'

apply plugin : 'org.owasp.dependencycheck'

apply plugin: 'war'

configurations.create('zipping')
// TODO: find how configuration can be renamed into 'server-original-data-store'
configurations.create('server_original_data_store')
configurations.create('javadoc_sources')
configurations.create('javadoc_compilation')
configurations.create('blast_tar')

dependencyCheck {
    nvd {
        apiKey = System.getenv('OWASP_NVD_APIKEY')
    }
    failBuildOnCVSS = 7 // 0 - 4 = low, 4 - 7 = medium, 7 - 9 = high, 9-10 = critical
    suppressionFile = "../owasp/owasp_suppressing_false_positives.xml"
    analyzers {
        assemblyEnabled = false
    }
    proxy {
        server = 'proxy.ethz.ch'
        port = 3128
    }
}

def jettyVersion = '12.1.1'

dependencies {
    api project(':server-screening')

    providedRuntime "org.eclipse.jetty:jetty-deploy:${jettyVersion}@jar",
            "org.eclipse.jetty:jetty-xml:${jettyVersion}@jar",
            "org.eclipse.jetty:jetty-security:${jettyVersion}@jar",
            "org.eclipse.jetty:jetty-server:${jettyVersion}@jar",
            "org.eclipse.jetty.ee10:jetty-ee10-annotations:${jettyVersion}@jar",
            "org.eclipse.jetty.ee10:jetty-ee10-jndi:${jettyVersion}@jar",
            "org.eclipse.jetty.ee10:jetty-ee10-plus:${jettyVersion}@jar",
            "org.eclipse.jetty.ee10:jetty-ee10-servlet:${jettyVersion}@jar",
            "org.eclipse.jetty.ee10:jetty-ee10-webapp:${jettyVersion}@jar",
            "org.eclipse.jetty.ee:jetty-ee-webapp:${jettyVersion}@jar"

    zipping "eclipse:jetty-distribution:${jettyVersion}@zip"

    blast_tar "blast:blast:2.2.30@tar.gz"

    server_original_data_store project(':server-screening'),
            //'bioformats:bioformats:6.5.1',
            'imagej:ij:1.43u',
            'cisd:cisd-openbis-knime-server:13.6.0.r29301',
            'apache:xml-apis:1.3.03',
            'slf4j:slf4j-api:1.7.24',
            'slf4j:slf4j-jdk14:1.7.24',
            'sybit:image-viewer:0.3.6'

    javadoc_sources project(path: ':lib-commonbase', configuration: 'archives'),
            project(path: ':lib-common', configuration: 'archives'),
            project(path: ':api-openbis-java', configuration: 'archives'),
            project(path: ':lib-openbis-common', configuration: 'archives'),
            project(path: ':server-application-server', configuration: 'archives'),
            project(path: ':server-original-data-store', configuration: 'archives'),
            project(path: ':server-screening', configuration: 'archives'),
            'sis:sis-base:23.06.0:sources',
            'cisd:cisd-args4j:9.11.2:sources',
            'cisd:cisd-hotdeploy:13.01.0:sources'

    javadoc_compilation project(path: ':server-screening')

    testImplementation project(path: ':lib-commonbase', configuration: 'tests'),
            project(path: ':lib-common', configuration: 'tests'),
            project(path: ':lib-dbmigration', configuration: 'tests'),
            project(path: ':lib-authentication', configuration: 'tests'),
            project(path: ':api-openbis-java', configuration: 'tests'),
            project(path: ':lib-openbis-common', configuration: 'tests'),
            project(path: ':server-original-data-store', configuration: 'tests'),
            'fjelmer:classycle:1.4.2',
            'testng:testng:6.8-CISD',
            'junit:junit:4.13.2',
            'org.springframework:spring-test:6.1.10'
    testImplementation(project(path: ':server-application-server', configuration: 'tests'))
}