buildscript {
    apply from: '../build/repository.gradle'

    repositories repositoryConfig

    repositories {
        ivy {
            ivyPattern "https://sissource.ethz.ch/openbis/openbis-public/openbis-ivy/-/raw/main/owasp/dependency-check-gradle/12.2.0/[organisation]/[module]/ivy-[revision].xml"
            artifactPattern "https://sissource.ethz.ch/openbis/openbis-public/openbis-ivy/-/raw/main/owasp/dependency-check-gradle/12.2.0/[organisation]/[module]/jars/[artifact]-[revision](-[classifier]).[ext]"
            artifactPattern "https://sissource.ethz.ch/openbis/openbis-public/openbis-ivy/-/raw/main/owasp/dependency-check-gradle/12.2.0/[organisation]/[module]/bundles/[artifact]-[revision](-[classifier]).[ext]"
        }
    }

    dependencies {
        classpath("org.owasp:dependency-check-gradle:12.2.0")
    }
}

apply from: '../build/javaproject.gradle'

apply plugin : 'org.owasp.dependencycheck'

dependencyCheck {
    nvd {
        apiKey = System.getenv('OWASP_NVD_APIKEY')
    }
    failBuildOnCVSS = 7 // 0 - 4 = low, 4 - 7 = medium, 7 - 9 = high, 9-10 = critical
    suppressionFile = "../owasp/owasp_suppressing_false_positives.xml"
    analyzers {
        assemblyEnabled = false
    }
    // Share DB across modules
    data {
        directory = "${projectDir}/.dependency-check-data"
    }
    skipConfigurations = ["testRuntimeClasspath", "testCompileClasspath"]
    // scanConfigurations = ["runtimeClasspath"]
    proxy {
        server = 'proxy.ethz.ch'
        port = 3128
    }
    scanProjects = [
            ":lib-logging",
            ":lib-commonbase",
            ":lib-common",
            ":api-openbis-java",
            ":lib-openbis-commonbase",
            ":lib-openbis-common",
            ":lib-openbis-messages",
            ":lib-authentication",
            ":lib-db",
            ":lib-dbmigration",
            ":lib-messages-db",
            ":lib-pathinfo-db",
            ":lib-pathinfo",
            ":lib-mail",
            ":lib-maintenance",
            ":lib-compress",
            ":lib-shuffling",
            ":lib-folder-monitor",
            ":lib-data-store-commonbase",
            ":lib-data-store-common",
            ":lib-hdf5",
            ":lib-hierarchical-content",
            ":lib-archiver-db",
            ":lib-archiver",
            ":lib-two-phase-transaction",
            ":server-application-server",
            ":server-original-data-store",
            ":server-screening",
            ":core-plugin-openbis",
            ":app-openbis-installer",
            ":lib-image-readers",
            ":test-api-openbis-javascript",
            ":server-external-data-store",
            ":ui-admin",
            ":lib-microservice-server",
            ":lib-transactional-file-system",
            ":server-data-store",
            ":ui-eln-lims",
            ":api-openbis-javascript",
            ":lib-json",
            ":api-data-store-server-java",
            ":api-data-store-server-javascript",
            ":api-openbis-typescript",
            ":test-integration",
            ":lib-rdf",
            ":docs",
            ":lib-ro-crate",
            ":app-ro-crate-openbis",
            ":app-migration",
            ":app-openbis-drive",
            ":app-openbis-command-line",
            ":test-app-openbis-installer",
            ":api-openbis-python3-pybis",
            ":release",
            ":owasp",
            ":server-ro-crate"
    ]
}
