apply plugin: 'java-library'
apply plugin: 'application'

//java {
//    toolchain {
//        languageVersion.set(JavaLanguageVersion.of(11))
//    }
//}

apply from: '../build/repository.gradle'
repositories repositoryConfig

apply from: '../build/common-resolutions.gradle'


dependencies {
    implementation project(':lib-logging')
    api     libs.org.eclipse.jetty.jetty.server,
            libs.org.eclipse.jetty.ee10.jetty.ee10.servlet,
            libs.org.eclipse.jetty.ee10.jetty.ee10.webapp,
            libs.org.eclipse.jetty.jetty.util,
            libs.jakarta.servlet.jakarta.servlet.api,
            libs.org.projectlombok.lombok,
            libs.com.fasterxml.jackson.core.jackson.annotations,
            libs.com.fasterxml.jackson.core.jackson.core,
            libs.com.fasterxml.jackson.core.jackson.databind,
            libs.org.slf4j.slf4j.api, // Required by Jetty that uses SLF4J
            libs.org.slf4j.slf4j.jdk14 // Required by Jetty to tell SLF4J to use JDK

    annotationProcessor libs.org.projectlombok.lombok
}

mainClassName = "ch.ethz.sis.microservices.download.server.startup.Main"
